### ISSUE TITLE
vendor: update vendored packages

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#1141]
Spring cleaning. Update all of the following packages to pull in latest code:

- [ ] github.com/beevik/etree (dep of SAML)
- [ ] github.com/coreos/etcd
- [ ] github.com/coreos/go-oidc
- [ ] github.com/ghodss/yaml
- [ ] github.com/go-sql-driver/mysql (maybe remove this?)
- [x] github.com/golang/protobuf (https://github.com/coreos/dex/pull/1140)
- [ ] github.com/gorilla/context
- [ ] github.com/gorilla/handlers
- [ ] github.com/gorilla/mux
- [ ] github.com/gtank/cryptopasta (maybe remove and just copy + paste code)
- [ ] github.com/inconshreveable/mousetrap (windows dep of cobra)
- [ ] github.com/jonboulle/clockwork (dep of SAML)
- [ ] github.com/kylelemons/godebug (test dep)
- [ ] github.com/lib/pq
- [ ] github.com/mattn/go-sqlite3
- [ ] github.com/pquerna/cachecontrol (dep of go-oidc)
- [ ] github.com/russellhaering/goxmldsig
- [ ] github.com/sirupsen/logrus
- [ ] github.com/spf13/cobra
- [ ] github.com/spf13/pflag
- [ ] golang.org/x/crypto (for bcrypt)
- [ ] golang.org/x/net
- [ ] golang.org/x/oauth2
- [ ] golang.org/x/sys
- [ ] golang.org/x/text
- [ ] google.golang.org/appengine (dep of oauth2)
- [ ] google.golang.org/genproto (dep of grpc)
- [ ] google.golang.org/grpc
- [ ] gopkg.in/asn1-ber.v1
- [ ] gopkg.in/ldap.v2
- [ ] gopkg.in/square/go-jose.v2
- [ ] gopkg.in/yaml.v2

**Comment by sks** [comment]
@ericchiang : Are you okay with deleting the `vendor ` directory and moving to `go modules ` ?

**Comment by ericchiang** [comment]
@sks I'd like to continue to commit `vendor`. even when we use `go modules` This helps us when repos get deleted from github.

**Comment by fishioon** [comment]
The vendored oauth2 not support custom param. 
So is time to update vendored packages. 😄

**Comment by srenatus** [comment]
#1501 ✔️ should be resolved
