### ISSUE TITLE
example app connection reset / no login

### ISSUE THREAD

**Issue by tuwid** [dexidp/dex#1146]
After starting the default config-dev.yaml and starting as well the default example app
In the "Navigate to the example app in your browser at http://localhost:5555/ in your browser." step i get a connection reset. In debug mode I can see the logs in the example app but nothing really happens. 

```
root@27d71e5119c8:/go/src/github.com/coreos/dex# ./bin/example-app --debug
2017/12/13 22:02:32 GET /dex/.well-known/openid-configuration HTTP/1.1
Host: 127.0.0.1:5556

2017/12/13 22:02:32 HTTP/1.1 200 OK
Content-Length: 693
Content-Type: application/json
Date: Wed, 13 Dec 2017 22:02:32 GMT

{
  "issuer": "http://127.0.0.1:5556/dex",
  "authorization_endpoint": "http://127.0.0.1:5556/dex/auth",
  "token_endpoint": "http://127.0.0.1:5556/dex/token",
  "jwks_uri": "http://127.0.0.1:5556/dex/keys",
  "response_types_supported": [
    "code"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "groups",
    "profile",
    "offline_access"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic"
  ],
  "claims_supported": [
    "aud",
    "email",
    "email_verified",
    "exp",
    "iat",
    "iss",
    "locale",
    "name",
    "sub"
  ]
}
2017/12/13 22:02:32 listening on http://127.0.0.1:5555

^C
```

This is running on a docker container. Ports are exposed and I tested connectivity with netcat by listening in one end and connecting to the other. 
Any ideas ?

**Comment by ericchiang** [comment]
Is it an issue with `localhost` not mapping to `127.0.0.1` or something?

**Comment by tuwid** [comment]
@ericchiang well it revolves around that but not really as testing with netcat worked but you can go around the issue by explicitly specifying the interfaces 
```
./bin/example-app --listen "http://192.168.111.42:5555" --redirect-uri "http://192.168.111.42:5555/callback" --issuer "http://192.168.111.42:5556/dex"
```

**Comment by nabokihms** [comment]
I’m closing this due to age. Feel free to reopen the issue if you still has a problem.
