### ISSUE TITLE
Provide a Readme document to setup dex on kubernetes versions ~> 1.8

### ISSUE THREAD

**Issue by nagarjunac** [dexidp/dex#1161]
I tried setting up dex on my Kubernetes cluster with version 1.8.2.
I found it hard to setup dex on kubernetes with the documentation provided. The third party resources are deprecated in 1.8 and It would be of great help if proper documentation is provided to setup Dex on kubernetes with versions >~ 1.8

**Comment by trinitronx** [comment]
I had good luck using [SEJeff/k8s-ldap][k8s-ldap] manifests as a starting point.  The README there is also pretty good.  It includes the new [CustomResourceDefinition manifests][1]

[1]: https://github.com/SEJeff/k8s-ldap/blob/master/dex-crd.yml
[k8s-ldap]: https://github.com/SEJeff/k8s-ldap

**Comment by whereisaaron** [comment]
Hi @nagarjunac there are [helm charts available](#1192) to install `dex` and `dex-k8s-authenticator` that work fine on k8s 1.8+.

1. `git clone git@github.com:mintel/dex-k8s-authenticator.git`
2. `helm inspect values charts/dex > dex.yaml`
3.  Edit 'dex.yaml' to suit your requirements
4. `helm install --namespace dex --values dex.yaml charts/dex`

**Comment by cceckman** [comment]
Maybe this just needs to be a  [documentation](https://github.com/dexidp/dex/blob/master/Documentation/kubernetes.md) update? It still refers to `ThirdPartyResources` rather than CRDs.

**Comment by nabokihms** [comment]
The issue is stale, so I am going to close it.

Dex now has an official Helm chart that works with the recent Kubernetes versions.
https://artifacthub.io/packages/helm/dex/dex

There is also an issue to improve getting started documentation.
https://github.com/dexidp/website/issues/78

Feel free to open a new issue if it is necessary.
