### ISSUE TITLE
Rebuild container images with fixed vulnerabilities

### ISSUE THREAD

**Issue by venezia** [dexidp/dex#1213]
Hi

All versions (but in particular the latest) of dex appear to have some vulnerabilities in their underlying environments.  [Quay](https://quay.io/repository/coreos/dex?tab=tags) lists 2 High security issues with v2.10.

Can we a get a rebuild/refresh to images that are no longer vulnerable?

Thanks

**Comment by sagikazarmark** [comment]
This should be fixed. We have enabled dependabot, so this should be automated in the future.
