### ISSUE TITLE
Cannot use `openid` scope in the GitLab connector

### ISSUE THREAD

**Issue by valer-cara** [dexidp/dex#1222]
### Usecase

I'm trying to pull groups from gitlab which requires the `openid` scope

### Problem

When specified by `--scopes=openid` flag dex redirects to an error page saying (url error only) "Unrecognized scope openid".

### Expected

Redirecting to gitlab and requesting the `openid` scope

---

Thank you for the good work on dex!

**Comment by ericchiang** [comment]
Hey @valer-cara, where's the --scopes flag coming from? dex doesn't use flags.

**Comment by valer-cara** [comment]
@ericchiang - sorry for the phrasing. i've been using [keycloak-proxy](https://github.com/gambol99/keycloak-proxy) and had some issues at the time. i'm currently asking for the `openid` scope and that works fine.

this is most probably no longer an issue. i'll close this one. thanks!
