### ISSUE TITLE
GitHub Non-Web application flow support

### ISSUE THREAD

**Issue by stepanstipl** [dexidp/dex#1225]
Is there a way to make non-interactive login via GitHub work? GitHub itself does support Non-Web application flow, where the OAuth2 token is statically pre-generated by user as a "Personal access token" (https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#non-web-application-flow).

Use-case: We would still like to use Dex for auth, but in a CI/CD context, where there's no possibility of interactively logging-in GitHub.

I imagine this could work by user creating "Personal access token" and then passing it to Dex, that would then use it directly to request additional info from GitHub and genereta access token to be exchanged for JWT token.

**Comment by ericchiang** [comment]
@srenatus that sounds like a service account.

If you're using dex with kubernetes, it's already got that concept: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/

Anything more would require a revocation UI. And given how bad our refresh revocation is, we probably want to tackle that first.

**Comment by nabokihms** [comment]
Dex now supports the token exchange feature. See for more details
https://github.com/dexidp/dex/blob/master/docs/enhancements/token-exchange-2023-02-03-%232812.md
