### ISSUE TITLE
Enabling SSL between Dex and quay container registry

### ISSUE THREAD

**Issue by sibu105636** [dexidp/dex#1227]
HI,
Did anyone configured dex as a OIDC provider to QUAY for AD authentication? I am stuck at enabling ssl between the two(Unfortunately quay does not allow http connection for OIDC clients). I am trying with self sign certificates in integration environment but getting certificate signed by unknown authority error even though I have trusted my CA. Both QUAY (running as a container) and dex are on the same host.

**Comment by srenatus** [comment]
This seems like a Quay-related question to me, I'm afraid? Dex should work fine with any provided TLS cert. Please re-open if this is still bugging you and there's someone on the Dex end that would help.

**Comment by sibu105636** [comment]
Hello Stephan, Yes it was a problem with my self sign certs.It's been fixed.  Thanks: Siba
