### ISSUE TITLE
Static clients' secret from environment variable?

### ISSUE THREAD

**Issue by fajran** [dexidp/dex#1241]
I am trying to setup static clients with secret taken from environment variable. Looks like currently Dex only support expanding environment variable for connectors and storage only.

Would expanding env var for client secret be something that can be supported by Dex?

thanks

**Comment by AlexMorreale** [comment]
i am also wondering about this i can't seem to get it to work with kubernetes secrets and env vars in the container

**Comment by ericchiang** [comment]
dup of https://github.com/dexidp/dex/issues/1099
