### ISSUE TITLE
Gitlab connector returns non-unique group names

### ISSUE THREAD

**Issue by davidarcher** [dexidp/dex#1246]
The GitLab connector at https://github.com/coreos/dex/blob/master/connector/gitlab/gitlab.go#L272 returns only the group name but GitLab supports nested groups so you can have two groups with the same name but different paths and those are two distinct groups.

I think we need to update Dex to use the group path for GitLab instead of just the name.

e.g.
I have a Gitlab group named "admins" located at "gitlab.example.com/myorg/myproject/admins". If I use Dex to authenticate, I only see "admins" which isn't usable because other users on the gitlab instance can create their own "admins" group that would look the same to Dex.

**Comment by devonbarrett** [comment]
This is fixed by: https://github.com/coreos/dex/pull/1224 which we're using and works well.

Would be nice to see that merged!

**Comment by davidarcher** [comment]
@devonbarrett Thanks! I searched issues but didn't search PRs before I opened this. It saves me having to open a PR :) I had one minor comment around keeping the path separator since GitLab is adding groups to their OIDC support directly.

**Comment by mvoelske** [comment]
It seems to me that this is no longer an issue: the Gitlab connector retrieves the list of groups from the `/oauth/userinfo` endpoint, and Gitlab (not sure since when) puts the full group path there.

**Comment by nabokihms** [comment]
Closing due to the previous comment. As of today, there is no problem with gitlab groups being unique.
