### ISSUE TITLE
How do I add a 'groups'  claim to a users record in the DEX DB?

### ISSUE THREAD

**Issue by jeffthompson1971** [dexidp/dex#1260]
I can't see any documentation on how to do this.  I want to use 'groups' to store the role I assign to a user so I have it in the id_token which will be passed around.   Struggling to find any info on that.

**Comment by soggiest** [comment]
@jeffthompson1971 Somewhat unrelated but I've written a pretty rudimentary Webhook Token Authenticator that enriches JWT Tokens with group information from an LDAP server. It may be useful to you: https://github.com/soggiest/cleathitch

**Comment by srenatus** [comment]
I'm afraid that's likely to be out of scope for Dex (in this incarnation) -- it's trying to be an federating identity provider, not a user (and group) management service. As such, there's no groups in Dex' users database, IIRC.

One option, I suppose, would be to create another connector. If this was done in a generic (enough) way, I could see this as a nice addition.

Let's open another issue for that if there's interest in it. Hope you don't mind that I close this (if you do, just reopen it 😉).
