### ISSUE TITLE
ignore auth page if client special one connector

### ISSUE THREAD

**Issue by fishioon** [dexidp/dex#1294]
First page list all connectors with  "/auth?client_id=&redirect_uri=&response_type=&scope=" .
When user choose one connector, then "/auth/{connector}?req=xxx".

Can support "/auth/{connector}?client_id=&redirect_uri=&response_type=&scope=&state="
so in my case, i can ignore  auth page and direct connector

**Comment by srenatus** [comment]
This is a bit related to #646. Right now, the auth request is created when visiting the first page, and then passed along to the selected connector (I think). To directly go to a connector's endpoint, we'd have to create the auth request there.

I'm torn when it comes it this. Yes, it would be helpful for simplifying some of our code, too. OTOH, it leads to leakage of internal information -- connector IDs -- and thus somewhat breaks the abstraction Dex provides.

That said, I'd be fine with this -- if we ensure that we adequately raise awareness of this issue in the docs... 🤔

**Comment by fishioon** [comment]
Thank you for the comment. 
We plan to deploy a oauth platform with dex.
And we will support many other connector like 'wechat, wework, miniapp, alipay' and so on.
In some case, client only can oauth with one connector and not select.
So can you help me?

**Comment by ericchiang** [comment]
> Can support "/auth/{connector}?client_id=&redirect_uri=&response_type=&scope=&state="
so in my case, i can ignore auth page and direct connector

If you only have one connector you'll automatically be redirected to the connector's login page.

The rest of this request seems like it could be fixed with https://github.com/dexidp/dex/issues/1084

**Comment by ericchiang** [comment]
Closing for now. I don't see anything in this request that's unique from #1084
