### ISSUE TITLE
what are dex' api endpoints?

### ISSUE THREAD

**Issue by yawboateng** [dexidp/dex#1313]
I searched through the docs and found:

"authorization_endpoint": "http://127.0.0.1:5556/auth",
"token_endpoint": "http://127.0.0.1:5556/token",
"jwks_uri": "http://127.0.0.1:5556/keys",

are there any other ones? in particular one for revoking refresh_tokens

**Comment by ericchiang** [comment]
Dex has a gRPC endpoint with this https://github.com/dexidp/dex/blob/master/api/api.proto
