### ISSUE TITLE
have a namespace scoped role for dex, instead of cluster-wide

### ISSUE THREAD

**Issue by SongGithub** [dexidp/dex#1332]
our current situation is that we have already got a DEX 2.10.0 deployed in kube-system namespace which is using `cluster-role`. This DEX has created necessary CRDs for all namespaces. 

For some reason, one of our teams want to deploy a separate DEX in their own namespace. And for security reasons, we only defined a `Role` that is namespace scoped. This Role leads to a problem that DEX can't create CRDs at cluster level and giving massive amount of RBAC-DENY alerts that triggering off our security alerts. 

The config for storage is kubernetes-in cluster 

I am wondering, can DEX not trying to create CRDs especially at cluster scope, if the CRDs are already existing in the namespace?

**Comment by SongGithub** [comment]
it appears to relate to this issue https://github.com/dexidp/dex/issues/1308 #1308

**Comment by SongGithub** [comment]
In particular, the code that leads to the problem is here
https://github.com/dexidp/dex/blob/218d671a96865df2a4cf7f310efb99b8bfc5a5e2/storage/kubernetes/storage.go#L149

could it check if CRDs already exist in the current namespace before going out to create CRDs?

**Comment by ericchiang** [comment]
I think this is a dup of #1308. We should probably just fix that.

**Comment by SongGithub** [comment]
Can I submit a PR for the fix please?

**Comment by SongGithub** [comment]
very happy to see the issue addressed by the above PR #1333, so I would like to close this issue.
