### ISSUE TITLE
Release v2.13.0

### ISSUE THREAD

**Issue by SongGithub** [dexidp/dex#1335]
It has been 25 days since Release v2.12.0. 

Wondering could we schedule a new release at Release v2.13.0?

**Comment by ericchiang** [comment]
I'd like to do a little testing in our CI for #1333 first

**Comment by ericchiang** [comment]
Sorry, ended up testing it manually. The debug messages are a little verbose, but it works :)

https://github.com/dexidp/dex/releases/tag/v2.13.0

**Comment by ericchiang** [comment]
Thanks for waiting. Tested the PR manually to verify it :)

This is now live. Will write the release notes tomorrow.

https://quay.io/repository/dexidp/dex?tab=tags
https://github.com/dexidp/dex/releases
