### ISSUE TITLE
Auth Redirect URL

### ISSUE THREAD

**Issue by ppolicherla** [dexidp/dex#1337]
With my app I provide the following url:
http://localhost:3002/auth/auth?response_type=code id_token&client_id=example&pfidpadapterid=htmlform&scope=openid profile email groups tenants&redirect_uri=http://localhost:3002/admin/oidc&nonce=" nonce "& **state=/admin/#/users**

the state object is the important bit I am looking at. That is how I am handling the redirects, so when a page is hit and a user is forced to sign in they are taken back to the page they were trying to access. However the URL that is being put in the browser is missing parts of the state:

http://localhost:3002/admin/oidc#access_token="a token"&id_token="some token"&**state=%252Fadmin%252F**&token_type=bearer

the state parameter is cut off. I have checked my code and the url looks the way it should, I get redirected to the dex sso. After signing in i get the above url with the missing bit.

**Comment by srenatus** [comment]
That's not a thing dex could do anything about:

Your client (browser) is requesting
```
http://localhost:3002/auth/auth?yadda=yadda&state=/admin/#/users
```
so the final `/users` is understood as the URI part called [**"fragment"**](https://en.wikipedia.org/wiki/Fragment_identifier) and that part is never sent to the server. So dex will only see a request for
```
http://localhost:3002/auth/auth?yadda=yadda&state=/admin/
```
and handle it properly: it's present in your final redirect, but URL-encoded -- twice:`%252F` is `%2F`, which is `/`.

So, to have this work for you, try to pass your state to dex in URL-encoded form, too. The state you get back should then contain your complete client-route.
