### ISSUE TITLE
Gitlab connector should not require the api scope.

### ISSUE THREAD

**Issue by gypsydiver** [dexidp/dex#1347]
As of now, the Gitlab connector requires users to grant the `api` scope to configured applications in order to retrieve information that could be just as easily pulled using read only scopes (`read_user`, `openid`).

The `/oauth/userinfo` endpoint provides all group information needed.

Can provide PR for this.

Related: #1222 
Solves: #1246

**Comment by srenatus** [comment]
Happy to take a PR there. ❤️  Could you please include some pointer to some current API docs?
