### ISSUE TITLE
LDAP: bring back connection pooling

### ISSUE THREAD

**Issue by srenatus** [dexidp/dex#1353]
Looking at #309 and the current code for the LDAP connector, that pooling behaviour wasn't carried over to dex v2. I would think i is a reasonable feature though, isn't it?

**Comment by ericchiang** [comment]
The code was really complicated and I felt that it didn't outweigh the benefits. If we have a use case that needs it, I'd be fine adding it back in.

**Comment by srenatus** [comment]
Well, I can't tell, really. I've come across one issue where this could have helped (new LDAP connections randomly failing); but it's not the obvious only solution to that.

Good to know that it wasn't forgotten but excluded for a reason 👍  I'll close this.
