### ISSUE TITLE
[LDAP connector] Add option to bind as user when performing group search

### ISSUE THREAD

**Issue by OwenTuz** [dexidp/dex#1361]
This is a feature request. I'm happy to have a go at implementing it, but wanted to raise it and see if people consider the design to be reasonable.

#### Suggestion

At the moment, the LDAP flow looks like this:

- Bind as BindDN, or anonymous bind if neither are provided
- Search for user
- Attempt to bind as user to confirm password is correct
- If groups scope is enabled, bind as one of (BindDN or anonymous) as above, and query the user's groups

However, by the second stage we know whether we have a working username and password, so we could just bind as that user when making the groups query, and remove the need for a service account.

For example, this could be added as a flag to the groupSearch section of the config file:
```
groupSearch:
  baseDN: dc=dex,dc=example,dc=com
  filter: "(objectClass=group)"
  bindAsUser: true
```

This would be nice in my organisation's situation as we allow anonymous binds to check if a user exists, but with no further access to the tree. Using this, we could avoid having to create a service account and pass a static password to Dex.

#### Pros
- Removes the need for a service account and static password in some configurations

#### Cons
- BindDN and BindPW must still be provided if anonymous access is completely disabled. This is already true and documented, but it may not be obvious if you expect `bindAsUser` to do all your work for you
- This could fail if the user does not have permissions to view their own groups? That particular configuration seems unlikely to me, but it's better not to assume
- This comes about because our organisation allows access to check usernames but not groups via anonymous bind. Is this configuration common enough to support?

The first two cons could be helped by clear documentation, but is the benefit worth potential confusion? Are there any other issues I'm missing?

**Comment by ericchiang** [comment]
If we do this we can't support refresh tokens. I'm okay with that, but it needs to be called out in the docs :)

**Comment by OwenTuz** [comment]
Interesting, thanks - wasn't aware of that aspect, I'll take a look into it.

**Comment by ericchiang** [comment]
If you'd still like to work on this, instead of adding an option, we could just make the service account username/password optional. When you don't provide one, the returned connector just wouldn't implement the RefreshConnector interface:
* https://godoc.org/github.com/dexidp/dex/connector#RefreshConnector

**Comment by OwenTuz** [comment]
That makes sense. Overall I'm tempted to close this, honestly - I'm not dead familiar with OIDC and the refresh token element didn't even occur to me, so I'm fine with not doing this if there's a solid reason.

Happy to work on this if it would be useful to anyone besides myself, but otherwise it risks just being one of those things that breaks and confuses you unless you read the documentation carefully. We can use a service account over here ¯\_(ツ)_/¯

Either way, thanks for the quick and helpful response!
