### ISSUE TITLE
userInfoURL for dex

### ISSUE THREAD

**Issue by melosalz** [dexidp/dex#1376]
Hi! I am trying to integrate nodejs with dex. What is the userInfoURL for dex?
I got the authorizationURL and tokenURL for dex as follow:
```
  authorizationURL: 'http://127.0.0.1:5556/dex/auth',
  tokenURL: 'http://127.0.0.1:5556/dex/token',
```

**Comment by srenatus** [comment]
There's no userinfo endpoint in dex right now. However, it's come up a few times, and there's a couple of open PRs, too: https://github.com/dexidp/dex/search?q=userinfo&type=Issues.

@melosalz Does this resolve the question? (Is it OK to close this?)

**Comment by melosalz** [comment]
@srenatus Thank you very much!
