### ISSUE TITLE
Discussion: Join CNCF?

### ISSUE THREAD

**Issue by kfox1111** [dexidp/dex#1379]
Is dex interested in joining the cncf?

**Comment by srenatus** [comment]
I, for one, think I'd like that, but I'm work-shy when it comes to pushing this forward 😅

**Comment by rithujohn191** [comment]
Yes, we have talked about this in the past. Definitely a great option. But have quite a bit to discuss and iron out before we do.

**Comment by kfox1111** [comment]
Its generally good to do as much community growing as early as possible. I can help reach out to the cncf if you are interested.

**Comment by srenatus** [comment]
@kfox1111 I'd be happy to help doing this. I suppose it's useful to have a few eyes on this, for drafting/reviewing documents etc.

**Comment by srenatus** [comment]
https://github.com/cncf/toc/blob/master/process/project_proposals.adoc Looks like this is the process?

**Comment by rithujohn191** [comment]
I could help put this together

**Comment by timothysc** [comment]
+1 - In talking with the maintainers today we are going to try and get the ball rolling on this.

**Comment by justaugustus** [comment]
I'm also able to help facilitate here.

**Comment by timothysc** [comment]
Folks, shall I take point on helping to drive the ball forwards here?

**Comment by sagikazarmark** [comment]
I'm personally not familiar with the process of donating a project to the CNCF, I had the impression that you are @timothysc and/or @justaugustus, so I think it would be a huge help if you could facilitate the with the appropriate channels.

I guess at some point the maintainers also have to be actively involved in the conversation at which point I'd be happy to join.

**Comment by JoelSpeed** [comment]
I would certainly appreciate if you could kick off the process @timothysc/@justaugustus, would it be best to mention some maintainers as points of contact when the issue is raised on the CNCF community side? Happy to be mentioned as a point of contact if that helps

**Comment by timothysc** [comment]
Process has started - https://github.com/cncf/toc/issues/363

**Comment by justaugustus** [comment]
Proposal PR opened here: https://github.com/cncf/toc/pull/379

**Comment by justaugustus** [comment]
Dex is now a CNCF Sandbox project: https://lists.cncf.io/g/cncf-toc/message/4853
Onboarding tracking can be found here: https://github.com/dexidp/dex/issues/1739
