### ISSUE TITLE
Question: Is secret expansion suppose to work in connectors?

### ISSUE THREAD

**Issue by darwin67** [dexidp/dex#1382]
Hi,

I'm currently playing around with Dex and am thinking of using it as the cluster authenticator for Kubernetes.

Referencing the example `dex.yaml`, using
- `$GITHUB_CLIENT_ID`
- `$GITHUB_CLIENT_SECRET`

for the github connector
https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml#L72-L73

will always crash the pod with the following error.
```bash
> kubectl logs dex-6457f4857b-fgftp
error parse config file /etc/dex/cfg/config.yaml: error unmarshaling JSON: parse connector config: invalid character '\n' in string literal**
```

Hard coding the credentials will get everything working so I'm wondering is secret expansion supposed to work for connectors in the first place?

I've been looking through issues and this repo, but I don't really see anything that clearly states secret expansion will work properly.

Also looking at the current Dex helm chart in the public repo, it seems to be storing the whole connector configurations in secrets, and is doing none of the things the docs is stating.

Is it just outdated documentation? If so, it'll be great if you can update it as I believe I've lost quite some amount of time not getting why this is not working as the instruction states.

As for the time being, is it recommended to just store the whole configuration in secrets like how your public helm chart is doing?

Thanks

**Comment by srenatus** [comment]
ℹ️ [This search](https://github.com/dexidp/dex/search?p=2&q=secret+connector&type=Issues) yields #1330 with a link to #1099. That last issue outlines how we'd solve the brittle stuff that goes on right now. Closing this in favor of that other issue. Help would of course be welcome 😃

**Comment by darwin67** [comment]
Yes, https://github.com/dexidp/dex/issues/1330 just reinforced what I'm experiencing right now.

I'm happy to help out, just not right now. :fox_face: 

It'll be great if you could still answer my initial question of what's the recommended way of putting credentials in the connectors since this functionality is likely broken for the time being?

**Comment by srenatus** [comment]
> It'll be great if you could still answer my initial question of what's the recommended way of putting credentials in the connectors since the secret expansion functionality is likely broken for the time being?

Sorry I was a bit fast on this one 😅 I'd say the recommended way is still what you've tried, with much applied care -- you might have to escape stuff in some way, it's hard to tell without knowing your secret.

> `invalid character '\n' in string literal`

There's no newline in your env vars, by any chance?

**Comment by srenatus** [comment]
> There's no newline in your env vars, by any chance?

Nope, I bet it's an `"` or `'`. Try escaping them in your env variable.

**Comment by darwin67** [comment]
@srenatus 
I'm sorry I can't share them since they are credentials.

> There's no newline in your env vars, by any chance?

There are no special characters, simpy characters for `[0-9a-zA-Z]` in the env var but here's what it looks like when I run `printenv` in that container

```sh
HOSTNAME=dex-78596c977c-dfhm4
GITHUB_CLIENT_ID=xxxxxxxxxxxxxxxxxxxx

GITHUB_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

DEX_SERVICE_HOST=10.108.178.160
DEX_PORT_443_TCP_PROTO=tcp
DEX_PORT_443_TCP_PORT=443
...
```

Is this the new line that it's complaining about?

**Comment by darwin67** [comment]
Ah okay, that was the issue :man_facepalming: 

The `\n` was also encoded when I ran
```
> echo "<secret-string>" | base64
```
so if I make sure I do it without echo and the plain string, it will work.

Thank you for helping! Closing this now.

**Comment by srenatus** [comment]
No worries 😃 Glad you've gotten past this 🎉
