### ISSUE TITLE
Refresh token changes to work with IFTTT

### ISSUE THREAD

**Issue by mtl-wgtwo** [dexidp/dex#1385]
Hi folks,

This is a great project, so thanks for all the effort in this.  

Recently I've tried to create a small project in IFTTT that would trigger an authentication with dex running locally in our cluster.  I found two stumbling blocks to this:

First, IFTTT passes the access_token, not the id_token to our service endpoint.  I found that patching in https://github.com/dexidp/dex/pull/1315 worked here.  Is there a chance that functionality could be approved and merged?

Second, IFTTT has a validation test called "Ensure older refresh token does not expire immediately".  I made a small patch to dex that (I think) enables this.  I'm more than happy to share this if it is something the dex project would like.  

I've seen some discussing that the existing behavior is by default -- I totally understand that, but I can also see the point of a small window for re-requesting a token as described here: https://platform.ifttt.com/docs/faq#authentication

Before I package up my changes and make a PR, is this something that the project would like?

**Comment by srenatus** [comment]
> First, IFTTT passes the access_token, not the id_token to our service endpoint. I found that patching in #1315 worked here. Is there a chance that functionality could be approved and merged?

Well, let's get a userinfo endpoint then 😄 It's really come up a lot, and I don't see why we shouldn't do it. I'll try to get a review done soonish... 😅 

> Second, IFTTT has a validation test called "Ensure older refresh token does not expire immediately". I made a small patch to dex that (I think) enables this. I'm more than happy to share this if it is something the dex project would like.

Do you still have the tabs open for the previous discussion here? I think this is something worth considering... after all, having only one shot for refresh-token exchange is a bit of a risk, indeed.
