### ISSUE TITLE
Grant repo write permissions to @joelspeed

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#1391]
Joel is an engineer at Pusher, who've been using dex since 2017. He's very familiar with the repo and using dex with Kubernetes:

https://thenewstack.io/kubernetes-single-sign-one-less-identity/

For the sake of involving Pusher in dex's development, I propose giving @joelspeed write access to this repo.

We'll hold off on quay access because of a lack of two party sign off (users can unilaterally push an image). The fewer users that have that capability the better.

cc @rithujohn191 @srenatus

**Comment by srenatus** [comment]
OK let's do that. Welcome, @JoelSpeed 🎉

**Comment by srenatus** [comment]
Done 🎉 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/870638/51799712-eb199480-2224-11e9-9ad8-80ff97a2ba8c.png">
