### ISSUE TITLE
Dex Operator for Kubernetes

### ISSUE THREAD

**Issue by briantopping** [dexidp/dex#1393]
Operator all the things! It seems like Dex would be a perfect fit for operators.

My guess there are too many other priorities and too few resources. I just thought I would leave this here. After spending the day getting my head around another Dex operator, I realize it is very deeply focused on their internal needs. And I presume they'd rather be using an upstream operator anyway.

Thanks for a great product!

**Comment by ericchiang** [comment]
Thanks! You're right that there's already a Dex operator under https://github.com/jenkins-x/sso-operator.

Going to close this since we don't have the bandwidth to maintain another project in addition to Dex. If you'd like for us to link to an operator in the readme though, feel free to send a PR :)

**Comment by briantopping** [comment]
Hi Eric, thanks for the feedback. If you give that operator a try, you’ll see why I filed this.

**Comment by ericchiang** [comment]
I'd file issues with that operator then. Or feel free to build your own. As stated, we don't have the bandwidth here to maintain one.

**Comment by briantopping** [comment]
Sure! I didn't ask anyone to do anything. Filing an issue sometimes helps shape long-term direction. I'm grateful this project exists and what everyone (including you) have done on it. Keeping ideas to oneself is even less of a contribution :-)

As for asking me to build one, I may do that. I have several operators that I am considering, doing "one more" may not be a big deal.

Cheers!
