### ISSUE TITLE
Mishandling of OAuth2 basic auth due to old golang.org/x/oauth2

### ISSUE THREAD

**Issue by cehoffman** [dexidp/dex#1406]
The golang.org/x/oauth2 dependency was incorrectly handling basic auth encoding of client id and secret. This was fixed in https://github.com/golang/oauth2/commit/13449ad91cb26cb47661c1b080790392170385fd. This bug presents as some confusion among OIDC configurations because of the basic auth unsupported flag. It is framed as being a bug on the providers side when in reality is a bug in dex via the oauth2 library. This causes inconsistency when communicating idP configuration to other installers.

**Comment by srenatus** [comment]
#1501 ✔️ should be resolved
