### ISSUE TITLE
Setup github actions for CI (was: Travis-CI alternatives)

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#1414]
Travis-CI has been amazing for Dex, but was recently acquired and undergone layoffs.

https://twitter.com/carmatrocity/status/1098538649908666368

Consider switching to another CI system.

**Comment by srenatus** [comment]
Looks like https://circleci.com/ and https://cirrus-ci.org/ are free for OSS.

**Comment by srenatus** [comment]
There's a new github feature we might be able to use here... 🤔

**Comment by srenatus** [comment]
I've signed up `dexidp` for the beta. Will post updates here.

**Comment by srenatus** [comment]
Github Actions became available. We just need a brave soul to create the yaml spec for running stuff there. 😃
