### ISSUE TITLE
Gitlab 11.10.1 Dex v2.16.0 show empty array of groups

### ISSUE THREAD

**Issue by davedastrange** [dexidp/dex#1437]
Hello,
User and login is successful but the groups array is empty with Gitlab Version 11.10.1.

`time="2019-04-28T05:25:51Z" level=info msg="login successful: connector \"gitlab\", username=\"dave\", email=\"dave@redacted.com\", groups=[]"
`
User dave is owner of one group in Gitlab.

Can someone confirm ?

**Comment by srenatus** [comment]
Can you share your configuration snippet used for the gitlab connector?

**Comment by davedastrange** [comment]
Of Course, but it's pretty much default.
`
  connectors:
  - type: gitlab
    # Required field for connector id.
    id: gitlab
    # Required field for connector name.
    name: GitLab
    config:
      # optional, default = https://gitlab.com
      baseURL: https://gitlab.redacted.com
      # Credentials can be string literals or pulled from the environment.
      clientID: not interessting
      clientSecret: not interessting
      redirectURI: https://dex.redacted.com/callback

`

**Comment by srenatus** [comment]
Have you allowed the proper scopes? https://github.com/dexidp/dex/pull/1351
did change the required scopes for gitlab...

**Comment by davedastrange** [comment]
The Application has the Scopes described in the docs. Like so https://github.com/dexidp/dex/blob/master/Documentation/connectors/gitlab.md

read_user (Read the authenticated user's personal information)
openid (Authenticate using OpenID Connect)

Interesting is that I cannot see a request in the Gitlab logs to https://gitlab.redacted.com/oauth/userinfo. In the code that seems to be the group information endpoint. Maybe something is wrong with my configuration.

Do you get get groups via the Gitlab connector ?

**Comment by srenatus** [comment]
Did your login request (sent to dex) include the "groups" scope?

**Comment by srenatus** [comment]
Any news? 😉 (...🧹can this be cleaned up?)

**Comment by srenatus** [comment]
3... 2... 1... 💥 😃
