### ISSUE TITLE
Enable Slack Github Integration and Notifications

### ISSUE THREAD

**Issue by devstein** [dexidp/dex#1445]
I want to subscribe to Dex Github notifications in my team's slack channel, but receive this error: 
```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
```

To reproduce:

1. Add GitHub app to Slack
2. Run `/github subscribe  dexidp/dex` in a slack channel

**Comment by ericchiang** [comment]
We've never configured Slack for this repo. If there's a bug it's in a different app. Sorry
