### ISSUE TITLE
Look into "Security Policy"

### ISSUE THREAD

**Issue by srenatus** [dexidp/dex#1451]
Github now supports a way to let users report _security issues_ in a non-public way (🎉). Maybe we should make use of this? The setup link is here: https://github.com/dexidp/dex/security/policy

cc @ericchiang @JoelSpeed what do you think?

**Comment by ericchiang** [comment]
Yeah I can do this. Probably better we stop linking to CoreOS's security notification email :smile:

**Comment by JoelSpeed** [comment]
> Probably better we stop linking to CoreOS's security notification email 

I was literally just about to say the same... 

Is there an announcement that talks about how this new feature works?

**Comment by srenatus** [comment]
I don't know. But I've stumbled upon https://github.blog/changelog/2019-05-23-maintainer-security-advisories/ which also seems quite useful.

**Comment by srenatus** [comment]
Ah, here you go: https://help.github.com/en/articles/adding-a-security-policy-to-your-repository

**Comment by JoelSpeed** [comment]
https://github.blog/2019-05-23-introducing-new-ways-to-keep-your-code-secure/#open-source-security this page also has some info on it. It looks awesome! Let me know if I can help in any way to set it up/test it

**Comment by ericchiang** [comment]
So the security policy is just a markdown document. I think setting up an email that isn't security@coreos.com is more important.

**Comment by JoelSpeed** [comment]
I was under the impression that the new features allowed users to submit security issues in a similar fashion to regular issues that could then be only seen by the contributors once submitted? Is this not the case?

Basically I thought we no longer needed an email

**Comment by ericchiang** [comment]
@JoelSpeed I'm dropping this per #1478 if you want to take it on :)

**Comment by sagikazarmark** [comment]
Closing in favor of #1867
