### ISSUE TITLE
LinkedIn connector fails with v1 APIs

### ISSUE THREAD

**Issue by tanmaykm** [dexidp/dex#1452]
The LinkedIn connector fails with an error like this:

```
time="...." level=error msg="Failed to authenticate: linkedin: get profile: 410 Gone: {
  \"errorCode\": 0,
  \"message\": \"This resource is no longer available under v1 APIs\",
  \"requestId\": \"....\",
  \"status\": 410,
  \"timestamp\": ....
}"
```

Looks like it needs to be updated to use v2 APIs, maybe these?
- https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api?context=linkedin/compliance/context#retrieve-other-members-profile
- https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/primary-contact-api?context=linkedin/compliance/context#retrieve-email-address
- https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq#how-do-i-retrieve-the-members-email-address

**Comment by srenatus** [comment]
Hm! That's unfortunate. Looks like there's a fork in the road here:
1. ditch the linkedin connector -- the current code is apparently broken
2. have someone chip in and fix it.

I'd lean towards (1.) but maybe someone steps forward? 😃

**Comment by tanmaykm** [comment]
Well, the changes look not too complicated and I can probably manage a PR in some time. But since this will be my first PR to this repo, it may need some iterations before being acceptable.

**Comment by srenatus** [comment]
@tanmaykm that's great news. Happy to assist you in any way there! :smiley: :tada:

**Comment by tanmaykm** [comment]
Thanks @srenatus, I have got something crude working. Will better it somewhat and put up a PR for review today.
