### ISSUE TITLE
OIDC connector insecureSkipEmailVerified flag is not used

### ISSUE THREAD

**Issue by pbochynski** [dexidp/dex#1455]
The documentation says:

> Some providers return claims without "email_verified", when they had no usage of emails verification in enrollement process or if they are acting as a proxy for another IDP etc AWS Cognito with an upstream SAML IDP
> This can be overridden with the below option
> insecureSkipEmailVerified: true 

But if "email_vierified" claim is missing the flag is never checked. It works only if the field exists and has boolean value. The code responsible for it is in here: https://github.com/dexidp/dex/blob/49e59fb54fb308c2cb17508232c28073964d3e35/connector/oidc/oidc.go#L220-L242

The configuration check should be moved up and claim `email_vierified` should not be retrieved if the flag is set to `true`

**Comment by srenatus** [comment]
That sounds accurate. Looks like this nuance got introduced in #1448, and I might even have asked for it... 😅 (All blame is on me!)

I'll look into it. Thanks!

**Comment by pbochynski** [comment]
Thanks for the quick response and really quick fix. I'm impressed!
