### ISSUE TITLE
Auto login for second app

### ISSUE THREAD

**Issue by cookie314** [dexidp/dex#1465]
I have multiple APPs that use dex to do authencation, LDAP.
When I access the first app, it redirect to dex to do authencation.
Then I access the second app, it redirect to dex, and i still need to input LDAP account.
It is possible that we can store the login state in dex, like in cookie? So that when I access the second app, it redirect to dex, dex auto login and redirect to app.
And it would be better if i can set a timeout for that session.
Thanks

**Comment by ericchiang** [comment]
dup of #32
