### ISSUE TITLE
LDAP Connector group poll

### ISSUE THREAD

**Issue by josh-ferrell** [dexidp/dex#1468]
The LDAP connector pulls the group membership when first authenticated and after the token has expired but in the interim group membership isn't updated. If you're using the default expiration time frame this means a user who has been removed from the group will retain access until the token is expired. 

As a feature request is it possible to include a group poll in the connector or a method for revoking specific tokens.

**Comment by srenatus** [comment]
There's no support for token revocation. Dex issues jwt id tokens that can be verified without contacting the issuer (dex).

What to do for your issue? We've been facing the same question and ended up with using very short lived id tokens, and making use of the refresh token mechanism to pull in the up-to-date group list.

**Comment by srenatus** [comment]
Do you mind if I clean this up? 😉
