### ISSUE TITLE
Skipping consent form

### ISSUE THREAD

**Issue by avkonst** [dexidp/dex#1471]
I have not found in the docs or in the closed issues. Is it possible to configure dex to skip (auto accept) consent form after a successful login? If it is not possible, I suggest to have it as a feature.

**Comment by srenatus** [comment]
You're referring to the approval screen? That can be skipped [by configuring it to be skipped](https://github.com/dexidp/dex/blob/cd3c6983da25a31a284082a3a3e7ce0b59d8b8c8/server/server.go#L67-L69). There are a few [open issues related](https://github.com/dexidp/dex/search?q=SkipApprovalScreen&type=Issues).

**Comment by srenatus** [comment]
Still an open question? Please re-open and provide more details 😃
