### ISSUE TITLE
Dex for nginx-ingress LDAP Authentication

### ISSUE THREAD

**Issue by perdurabo93** [dexidp/dex#1475]
I've got a working dex auth connector to LDAP that's being leveraged by Kuberos for user authentication.  I want to leverage the same instance of dex I have in my K8S cluster to act as an nginx ingress authenticator for UIs that dont have their own LDAP auth.  I've been successful with this example of basic htpasswd->K8S secret ingress auth here:

https://github.com/kubernetes-retired/contrib/tree/master/ingress/controllers/nginx/examples/auth

But I want to to configure any ingress to authenticate to dex which is connected to my LDAP/AD to authenticate my ingress.  Are there any examples of what nginx.ingress.kubernetes.io/* annotations to add to my ingress.yaml to use to achieve this?

**Comment by sagikazarmark** [comment]
Please open a question under Discussions if this is still relevant.
