### ISSUE TITLE
Token exchange for external tokens

### ISSUE THREAD

**Issue by onatm** [dexidp/dex#1484]
Is there any plans to add a token exchange for the access tokens of connectors?

[`keycloak`](https://github.com/keycloak/keycloak) has this functionality. If there is a plan to add it then I'd be happy to go on and create a PR for it.

You can find the documentation of their external token exchange [here](https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/token-exchange/token-exchange.adoc#internal-token-to-external-token-exchange).

**Comment by srenatus** [comment]
Thanks for providing links! There's currently no _plans_ or a roadmap or anything here -- Just a few people spending some spare time on keeping this from rotting away 😉  -- So, unless there's someone implementing it, that is. Would you want to be that person?

If so, let's sketch out how this is going to look like before diving into the code, please. It seems like a bigger endeavour than what you'd commonly _"just send a PR for"_ 😃

**Comment by onatm** [comment]
I definitely want to be that person 😄 

I'd be happy to share ideas and discuss the best possible way to implement it. Where is the best place to continue the conversation? Here or gitter or discord?

**Comment by srenatus** [comment]
💯-- great.

I'm afraid I am still lacking a complete idea how this is going to look like, and what you'd achieve with that. My current best guess (after merely skimming the linked docs): you're exchanging a connector-id-token for a dex-id-token? So, this would only apply to using the OIDC connector? Or what's the intended scope here? 😃

**Comment by onatm** [comment]
Your guess is half right 😄 It is for exchanging a dex `id_token` with a connector `access_token`. I've already implemented a super naive version of it by only having `github` connector in mind.

You can check the implementation here: https://github.com/onatm/dex/tree/external/token-exchange

**Comment by srenatus** [comment]
Right now, it's quite nice that dex works like a funnel with many external identity providers on the top side, and a single OIDC IdP for anything _below dex_... This would break this abstraction, wouldn't it? 🤔

**Comment by onatm** [comment]
I think this would not break that abstraction (_and it shouldn't_). `ConnectorData` is already stored in the backing data store and it would be a shame not to use that data 😃.

The implementation I've done accepts an `idToken` with some required parameters (based on `keycloak` specification) and returns the `ConnectorData` to the caller. dex still on the top side and now behaves like a bridge between the client and underlying identity provider.

**Comment by onatm** [comment]
I forgot to add: to be able to use this _token exchange_, the `idToken` should have `federated_claims` in it.

**Comment by srenatus** [comment]
Can you help me get more of the overal picture? What's the use case for you, what client is doing the token exchange stuff, and what for? 😃 (Really just curious)

**Comment by onatm** [comment]
Sure, let me try to explain (I might misuse some terms):

Currently, I have a single page web application which uses [`oidc-client`](https://github.com/IdentityModel/oidc-client-js) to make an `implicit_flow` request. `dexidp` provides only the `github` connector and act as the authorization server for an API. The tricky part is API here is not the only resource owner; github is also another resource owner which is called by the API. That's why I need to acquire github access token.

I hope it makes sense 😃

**Comment by srenatus** [comment]
Hrm. I'm having a hard time drawing a line. To be honest, the appeal of Dex to me always has been, among other things, that _it's not keycloak_ -- the feature set of Dex is overseeable.

But there seems to be some people who want this? I count four :+1:s at the moment...

Still, this doesn't feel quite right. We've got ten connectors, and the ones for which a feature like this would *not work* are:
- ldap
- saml
- local users (not a real connector, but it's all the same to a user of dex, I think)

and perhaps a few others (I don't know the intricacies of what tokens get exchange for microsoft or linkedin).

Also, there's is nothing _common_ here, among multiple connectors. I.e. if your application uses Dex only uses Dex for logging in via github, it's a different use case as when your application uses Dex for logging in with a wider selection of connectors. In the latter case, you won't care much about which connector the user has actually used, and just treat them as "logged in". (This is how I've been thinking of Dex, a building block for abstracting identity providers.) Correct me if I'm wrong (of course! 😄) but in the end, this feature is focussed on the dex-for-login-via-one-connector-only usecase, and improves the feature set for that, isn't it? 🤔

**Comment by onatm** [comment]
> Still, this doesn't feel quite right. We've got ten connectors, and the ones for which a feature like this would _not work_ are

I guess this could work with OAuth2 providers including microsoft and linkedin.

> Also, there's is nothing _common_ here, among multiple connectors. I.e. if your application uses Dex only uses Dex for logging in via github, it's a different use case as when your application uses Dex for logging in with a wider selection of connectors. In the latter case, you won't care much about which connector the user has actually used, and just treat them as "logged in". (This is how I've been thinking of Dex, a building block for abstracting identity providers.) Correct me if I'm wrong (of course! 😄) but in the end, this feature is focussed on the dex-for-login-via-one-connector-only usecase, and improves the feature set for that, isn't it? 🤔

What you are saying is totally making sense. However, this feature can be scoped down only for OAuth providers and does not contradict with Dex's overseaable feature set.

What would be the best possible way to get external idp access tokens in a scenario where Dex is used?

**Comment by wedow** [comment]
@onatm is this something you're still interested in exploring? I'd like to take a stab at it based on your WIP branch as this is currently my only blocker in adopting dex.

**Comment by onatm** [comment]
@wedow I ended up implementing my own implicit flow only OIDC provider with opinionated identity management - you can see it [here](https://github.com/onatm/heimdall). If we can agree on an implementation w/ the maintainers of this project I can help in implementing this feature.

**Comment by sagikazarmark** [comment]
Closing as there is a more recent issue
