### ISSUE TITLE
Graceful shutdown should be supported

### ISSUE THREAD

**Issue by liyimeng** [dexidp/dex#1523]
Today, dex dose not handle any signal from user or kubernetes. This might cause some resource open when dex process are killed, e.g. the storage.Close function never get called.

**Comment by nabokihms** [comment]
I think this issue was resolved in #1942

**Comment by sagikazarmark** [comment]
Hm, is storage.Close also called somewhere?

**Comment by nabokihms** [comment]
I don't think so 😅 . Looks like we have to add it.
