### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Joematpal** [dexidp/dex#1527]
I looked for a similar issue. Maybe I over looked the ticket if it was there. 

I'm having trouble resolving this error. I'm using the k8s deployment from the example. 

The pod will not start up.
When I "kubectl logs $POD" this is the error I get. I don't know where go to try and see whats causing this error to try and fix it. Or... even if I can fix it.

**Comment by venezia** [comment]
Can you provide a bit more context?
* What container image of dex
* What version of kubernetes
* Are you running kubernetes in an amd64 environment?
  * The error you cite is a docker error, specifically when the binary isn't considered executable, etc.

The example deployment requires some configuration as well.

FWIW, I just tried the example, and while it needs adjustment (adjustment of TLS settings, github api keys, etc.) it does run for me.

**Comment by Joematpal** [comment]
Thanks for the help.
```
kubectl version
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCom mit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate: "2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/arm 64"}
```

```
lscpu | head -1                                              
Architecture:        aarch64
```
I can post my all of my yaml files. I'm just don't really know where to look to try and debug this one. I'm running the k8s on a pi cluster. Other app that I've written work fine. My Postgres and Cassandra databases are working fine. I'm just really stumped by this error. Thank you for your time and help.

**Comment by venezia** [comment]
@Joematpal you're running on arm - so the images listed in the example will not work.  Do you need help building an aarch64 version of dex?

@srenatus Should quay offer images of dex compiled for aarch64?  Its not hard to cross compile, etc.

**Comment by Joematpal** [comment]
I could try and build it. I would love any help during the build process.

**Comment by Joematpal** [comment]
I built it and pushed it to a public docker repo.
https://cloud.docker.com/repository/docker/joematpal/dex

This is my deployment: https://github.com/Joematpal/dex-k8s-deployment
I'm getting this error now. 
```
error parse config file /etc/dex/cfg/config.yaml: error unmarshaling JSON: parse connector config: invalid character '\n' in string literal
```
Which is confusing because I'm passing in a yaml file.

**Comment by venezia** [comment]
* That's great that you were able to build dex in linux/arm64
* If you're getting that then the config that is mounted through the configmap must have some form of invalid yaml in it.  Given that the link you gave is pointing to the original dex repo (and not yours) perhaps there are other changes as well.
  * look at https://github.com/Joematpal/dex-k8s-deployment/blob/master/dex_configmap.yaml#L7-L39, but in your local copy
  * remove the lines above, remove the indentation - does it still pass a yaml validator?

Hope that helps

**Comment by Joematpal** [comment]
@venezia I cut out the bits you said and it passes a yaml validator.

**Comment by venezia** [comment]
I still think it is having trouble parsing your configuration.

If you don't mind, for the moment, adjust line 18 on [your deployment](https://github.com/Joematpal/dex-k8s-deployment/blob/master/dex_deployment.yaml#L18) to be ```command: ["/bin/sleep", "999999"]```, apply the change, then do something like:

```shell
kubectl -n <dexNamespace> exec -it <dexPodName> cat /etc/dex/cfg/config.yaml
```
this may look like
```shell
kubectl -n dex exec -itdex-f765a36d4-abcde cat /etc/dex/cfg/config.yaml
```
you can get the pod name by looking at 
```shell
kube -n <dexNamespace> get pods
```
Does this still pass validation?

**Comment by Joematpal** [comment]
``` shell
✘ josephpalacio@ba91be5a  ~  kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
busybox                     1/1     Running   166        6d23h
dex-7848d9d5-lfxs6          1/1     Running   0          106s
postgres-6c497f4464-m9kgt   1/1     Running   0          7d
registry-5f9ffbfd86-pp9gj   1/1     Running   0          6d23h
 josephpalacio@ba91be5a  ~  kubectl exec -it dex-7848d9d5-lfxs6 cat /etc/dex/cfg/config.yaml
issuer: https://dex.example.com:32000
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    redirectURI: https://dex.example.com:32000/callback
    org: kubernetes
oauth2:
  skipApprovalScreen: true

staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```

Yes it passes a validator. Idk what the issue is. When I run it locally (bin/dex server $YAML_FILE) it still doesn't like that file. Even though it's passed the validators. I ran the github.com/dexidp/dex/examples/config-dev.yaml locally as well it worked fine.. so its not the executable.

**Comment by Joematpal** [comment]
Ok so when I ran that yaml output again through my local build of dex on the a raspbery pi. I takes it just fine. I deleted the deployment and reapplied it. No luck. It didn't work. I'm trying to rebuild the docker image, maybe that is the issue.

**Comment by venezia** [comment]
That's somewhat perplexing.  That being said, have you considered installing dex through helm?  There are many charts floating around, but I think [this one](https://hub.kubeapps.com/charts/stable/dex) is maintained and I personally used [this one](https://github.com/mintel/dex-k8s-authenticator)

I wonder if you have any better results using those charts.  Mind you - you will have to adjust it to use your custom arm64 docker image.

**Comment by Joematpal** [comment]
Thats a good idea. Thank for you help. You got me passed the "exec format error". I'm going to make this as closed. If anyone runs into this error and they are trying to run on arm you'll have to build for arm and deploy that docker container. I can try to keep and up-to-date image on cloud.docker.com/repository/docker/joematpal/dex. That images should at least be a good test for anyone trying to trouble shoot this issue.

Thank you, @venezia. I owe you a cup of coffee. ;)
