### ISSUE TITLE
OPTIONS /userinfo denied on Access-Control-Request-Headers: Authorization

### ISSUE THREAD

**Issue by rikardev** [dexidp/dex#1532]
Hi,

I have a client that sends an OPTIONS request to the /userinfo endpoint with an `Access-Control-Request-Header: authorization`. This seems correct to me but dex replies with 403 since no Allowed CORS Headers are configured.

Implementing the handleWithCors func in server.go like this would be an easy fix:
```golang
handleWithCORS := func(p string, h http.HandlerFunc) {
	var handler http.Handler = h
	if len(c.AllowedOrigins) > 0 {
		allowedOrigins := handlers.AllowedOrigins(c.AllowedOrigins)
		allowedHeaders := handlers.AllowedHeaders([]string{"authorization"})
		handler = handlers.CORS(allowedOrigins, allowedHeaders)(handler)
	}
	r.Handle(path.Join(issuerURL.Path, p), instrumentHandlerCounter(p, handler))
}
```

Is that a viable solution? Am I missing something?

**Comment by rikardev** [comment]
Clients running in Firefox seems also to complain about missing Access-Control-Allow-Methods header. That seems dirtier to solve however since gorilla isn't setting any unless the Access-Control-Request-Methods header contains a value separate from the Gorilla defaults (GET, HEAD, POST).

So just using `handlers.AllowedMethods([]string{"POST", "GET", "HEAD", "OPTIONS"})` for example with a request containing the header `Access-Control-Request-Method: GET` will not yield a 'Access-Control-Allow-Methods: GET' header in the response.

**Comment by HEllRZA** [comment]
I had the same issue with CORS on the /userinfo endpoint. As i understand CORS, the preflight on OPTIONS should not return 4xx at all, but a 200 with the correct CORS headers. Then the browser should check the CORS Headers.

Is this behavior considered more secure?

**Comment by al45tair** [comment]
This still needs fixing, and it's now October 2020. @HEllRZA has a fix in his PKCE implementation, but has said he'll remove it as it isn't related to PKCE. So, @HEllRZA, are you going to submit it as a separate PR? If not, please let me know and I'll raise one myself. It needs fixing for what I'm working on, and I don't want to have to maintain a Dex branch forever just for this.

**Comment by sagikazarmark** [comment]
I'm wondering if it would make sense to add this header to the userinfo request only. But I guess it's fine to add to the "global" middleware and iterate if necessary.

I will gladly accept a PR, I only raised the question in the PKCE PR whether it was related to that change. A separate PR would probably be better.

**Comment by al45tair** [comment]
@sagikazarmark @HEllRZA OK, well as it's a tiny change and I need it, I've submitted a PR. I couldn't find anywhere a statement about what you want your commit messages to look like, so I've guessed.

**Comment by tkleczek** [comment]
@sagikazarmark /token endpoint also allows for HTTP Basic Auth, so Authorization header should be allowed there as well.
