### ISSUE TITLE
Central revocation of refresh tokens

### ISSUE THREAD

**Issue by mvijftigschild** [dexidp/dex#1546]
This issue has similarities with https://github.com/dexidp/dex/issues/1203
However, that issue has no solutions since the poster found a workaround

Our situation:
We use Dex to have our developers get CLI access to Kubernetes with a combination of:
* Dex
* Dex connector to ldap
* Kubelogin

We are currently not using refresh tokens, but all it would take for someone to get a refresh token is to add 'offline_access' to their ~/.kube/config.
Because we want our users to log in at least once a day, in case a machine gets compromised, we want to be able to revoke refresh tokens from a central location.

Using the documentation and code here we are trying to:
Create a (cron)job running on K8s that does the following:
* Do an Ldap query to get all the usernames of our users
* Retrieve the refreshTokens for each user using "client.ListRefresh"
* Revoke the refreshTokens older than <timestamp> using RevokeRefreshReq
Note that this K8s job is not running within Dex server, but is running within the same K8s namespace and does have access to configMaps and secrets created by Dex.

The issue:
According to https://github.com/dexidp/dex/blob/master/api/api.proto

```
// ListRefreshReq is a request to enumerate the refresh tokens of a user.
message ListRefreshReq {
  // The "sub" claim returned in the ID Token.
  string user_id = 1;
}
```
We see that the user_id is actually the "sub" claim which is returned as part of the JWT.
When we look at the "sub" of a JWT, we can see that it's protobuf and base64 encoded and contains the username followed by the connector id. So something like:
"foo.barldap"

However, because we want a Cronjob on K8s to do the revocation of the tokens, we don't have the tokens of the users. Therefore we would need to construct this user_id. 
Seems simple enough, take the username from the ldap query, add "ldap", encode using protobuf and base64.
In https://github.com/dexidp/dex/blob/master/server/internal/codec.go we see the Marshal and Unmarshal methods we would need.

Unfortunately we can't use these, since they are internal. 

Speaking from far down the rabbit hole, I'm afraid I either missed something obvious, or Dex is not designed to cater to this usecase. 
If I missed something here I hope someone can help. 
I'd hate to have to abandon Dex because of something as simple as expiration of refreshTokens.

**Comment by jseadragon** [comment]
I'm also interested in hearing more from someone about this use case. I am looking to use Dex as an LDAP connector, and I'd like to have Dex periodically sync the LDAP group memberships with the RBAC memberships we have setup. In this way, if I grant someone access to a role, it will automatically propagate.

**Comment by jseadragon** [comment]
So, I did a bit of digging... and LDAP synchronization seems to work. https://github.com/dexidp/dex/issues/1203#issuecomment-613151280

**Comment by nabokihms** [comment]
You can set the `absoluteTokenLifetime` for refresh tokens if you want users to login every day.
Also, if you want them to log in if they didn't use the application for some time, you need to set the `validIfNotusedFor` option.

For more details, see https://dexidp.io/docs/id-tokens/#expiration-and-rotation-settings
