### ISSUE TITLE
UserInfo endpoint only providing very basic info

### ISSUE THREAD

**Issue by FOTempel** [dexidp/dex#1552]
I'm trying to hook Rocket.Chat to DEX as OAuth provider. Rocket.Chat expects an /userinfo endpoint. I'm able to succesfully authenticate through DEX with the SAML backend, but I'm unable to get anything useful out of it as Rocket.Chat doesn't get the additional information it needs from the /userinfo endpoint. All I get as "identity response" (according to Rocket.Chat) is:
`server.js:212 CustomOAuth ➔ debug Identity response {
  "iss": "<URL>",
  "sub": "ChRGLlRlbXBlbEBvbnQuY2ppYi5ubBINc2FtbC1hZGZzLW9udA",
  "aud": "rocketchat-dev4",
  "exp": 1569403980,
  "iat": 1569317580,
  "at_hash": "RQ6693wq7O-NjVWo2UcOow"
}`
Now that's nice and all, but I need a username, email and some groups at the very minimum. I've been looking at the source of both projects and all I can see is that Rocket.Chat parses the JSON it receives from DEX and DEX sends all claims from "idToken" (which seems to come from the request "authorization" header) as JSON. So with my limited grasp of authentication and authorization I kinda assumed I'd get the same stuff as what's returned with the example app (name , email and email_verified). Basically, my question is whether or not idToken actually contains the fields I need in its claims. And if not, how do I tell Dex to include them?

**Comment by FOTempel** [comment]
Nevermind. It all had to do with scopes. Hah!

**Comment by mvdkleijn** [comment]
@FOTempel Would you mind closing this issue if it is no longer valid?
