### ISSUE TITLE
web templates: use relative URLs for static assets

### ISSUE THREAD

**Issue by yanniszark** [dexidp/dex#1553]
Hi all,
first of all I'd like to thank you for this great project.

While using Dex I noticed that the page's static assets are fetched using an absolute URL vs a relative one:

https://github.com/dexidp/dex/blob/8427f0f15cbc870e275b429dd8afaa69b61b8d1d/web/templates/header.html#L8-L10
https://github.com/dexidp/dex/blob/8427f0f15cbc870e275b429dd8afaa69b61b8d1d/server/templates.go#L142

This makes the pages break if the user is accessing Dex behind a proxy.
I believe it's reasonable for the web pages to use relative URLs in order to accommodate this use-case, since it doesn't seem to be a big change.

Would you be open to a PR fixing this?

**Comment by yanniszark** [comment]
/cc @srenatus
What do you think about using refering to those assets in a way relative to the current page's path?

eg 
top level pages would specify `../assets/main.css`
2nd level pages (eg /auth/{connector}) would specify `../../assets/main.css`

The issue is that all pages use the same header template, so we need a way to propagate that information to template generation.

I am able to dedicate cycles to implement this feature and I would love some feedback :smile:

**Comment by srenatus** [comment]
> This makes the pages break if the user is accessing Dex behind a proxy.

Does it? I think the usual thing to do is to reverse-proxy `ISSUER-URL/dex` to dex, so it wouldn't matter. 🤔 

> I believe it's reasonable for the web pages to use relative URLs in order to accommodate this use-case, since it doesn't seem to be a big change.

However, the first point notwithstanding, you're right here, I think.

> I am able to dedicate cycles to implement this feature and I would love some feedback 😄

Sure! 😃 It seems like a decent improvement, although I'm not convinced that it would unblock that many scenarios. 😉I might just be missing something here.

**Comment by yanniszark** [comment]
Thanks a lot for the feedback @srenatus !
To give you a better view of the current problem, consider the following:

* A user navigates to `example.com/dex` and logs in.
* A user navigates to `localhost/dex`, which is reverse proxied to `example.com/dex` (like port-forward in Kubernetes). Since the login page requests things from `examples.com/dex/assets/main.css` and not from a relative `../../assets/main.css`, the page will break.
