### ISSUE TITLE
`expire_in` is not configurable

### ISSUE THREAD

**Issue by lohmag** [dexidp/dex#1577]
https://github.com/dexidp/dex/blob/master/server/server.go#L75

I use dex with LDAP provider and 24h interval is too low for everyday use. Even the people who work with k8s every day needed to recreate it almost every day. And this interval is not configurable at all.

**Comment by bonifaido** [comment]
Please check https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml#L38
