### ISSUE TITLE
Can't depend on latest dex with Go modules

### ISSUE THREAD

**Issue by stevendanna** [dexidp/dex#1578]
If you depend on `github.com/dexipd/dex`, the Go modules system will currently pin you to `v2.13.0`.

It picks up this old version because that is the last version in which dex _wasn't_ using Go modules.  It does this because two other rules in the Go modules systems make the newer version unusable. Since Dex has opted in to modules, Go modules assumes that v2 should be in the import path somewhere:

https://sum.golang.org/lookup/github.com/dexidp/dex@v2.19.0
```
not found: github.com/dexidp/dex@v2.19.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
````

And, since Dex has opted in to modules, the "+incompatible" workaround is also disallowed:

https://sum.golang.org/lookup/github.com/dexidp/dex@v2.19.0+incompatible
```
not found: github.com/dexidp/dex@v2.19.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

Currently we've worked around this with a `replace` directive.

There is information here on possible paths forward https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher although, it doesn't appear to me to be easy to solve without at least 1 breaking change for users.

**Comment by djboris9** [comment]
Hi @stevendanna 

May I ask how you manged to work around this issue with a `replace` directive?

Kind regards,
Boris

**Comment by slok** [comment]
Hi @djboris9! although I'm not @stevendanna, what I've done myself and I see the cleanest approach (IMHO) is to pin to the commit(https://github.com/dexidp/dex/commit/d820fd45d80cef74d4c65f5fcc5766ddb1fa514e) of the tag I want ([v2.23.0](https://github.com/dexidp/dex/tree/v2.23.0)).

```
require (
    // ...
	github.com/dexidp/dex d820fd45d80cef74d4c65f5fcc5766ddb1fa514e // Same as v2.23.0
   // ...
)
```

then `go mod tidy`, and you will end with something like:

```
require (
    // ...
	github.com/dexidp/dex v0.0.0-20200303100508-d820fd45d80c // Same as v2.23.0
   // ...
)
```

**Comment by sagikazarmark** [comment]
Can I ask why you would want to depend on Dex? It's an application, not a library.

BTW, the solution outlined by @slok is the correct one in this case.

**Comment by slok** [comment]
Well... It has a GRPC API and it has Go client generated.

https://github.com/dexidp/dex/blob/master/api/api.pb.go#L1336

I use it to register clients dynamically.

**Comment by djboris9** [comment]
Thanks @slok for this hint, it works perfectly!

I use it for testing and development a Go application, where a port is dynamically chosen and the clients and paths are set up according to the environment. The code for spinning up and terminating an appropriately configured dex server is ~100 LOC long without any special logic.

Starting and managing a different process and configuring it with gRPC requires much more logic for such short lived procedures.

**Comment by stevendanna** [comment]
We had originally forked the repo, but I think the pinning outlined by slok is cleaner and will probably move to that.

> Can I ask why you would want to depend on Dex? It's an application, not a library.

I believe we use it for similar reasons as those mentioned: The API client and starting a test dex server in some of our functional tests.

**Comment by sagikazarmark** [comment]
This should be fixed by https://github.com/dexidp/dex/releases/tag/api%2Fv2.0.0
