### ISSUE TITLE
helm [stable/dex] Cannot override config.connections in subchart

### ISSUE THREAD

**Issue by deschmih** [dexidp/dex#1580]
I use for installation of dex `helm v3.0.0-beta.4`, `stable/dex` from https://github.com/helm/charts/tree/master/stable/dex and a `customize-value.yaml` to add multiple-connectors.

The `customize-value.yaml` to add this connectors is in style like this:
```
...
config:
  conectors:
  - type: ldap
    ...
  - type: github
    ...
...

```
The installation succed, but I get an warning that `connectors` is not map!
```
$ helm install dex stable/dex -f customize-vaules.yaml
coalesce.go:186: warning: cannot overwrite table with non table for connectors (map[])
NAME: dex
LAST DEPLOYED: Thu Nov  7 14:06:04 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w dex'
  export SERVICE_IP=$(kubectl get svc --namespace default dex -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo https://$SERVICE_IP:
```
 And this is ture. Connectors in `stabel/dex` `values.yaml` is not a map. It is described as:
```
...
  connectors: {}
...
```

see also: https://github.com/helm/charts/issues/17768

**Comment by deschmih** [comment]
@rendhalver Can I address this issue direcly to you?
I have seen in #1192, that you had some activity to bring this to helm hub.
I would be nice to have issue this fixed.

**Comment by gabibbo97** [comment]
Hi, I have a PR that was merged today https://github.com/helm/charts/pull/17682 that attempted to fix this, let me know if it worked

**Comment by deschmih** [comment]
@gabibbo97 It works fine for me. Thanks.
