### ISSUE TITLE
dex.io in log file

### ISSUE THREAD

**Issue by jmwilkinson** [dexidp/dex#1587]
In deploying this I see the following in the log:

```
time="2019-11-19T19:08:29Z" level=info msg="config issuer: http://dex.io:8080"
```

But dex.io is some kind of cryptocurrency exchange. So what is going on here?

**Comment by bonifaido** [comment]
What do you mean by deploying this? How did you deploy dex? Issuer is a configurable value and it should be your domain.

**Comment by jmwilkinson** [comment]
@bonifaido Oh, that clarifies things a bit. I was using a Helm chart. Very strange default value. Is the helm chart maintained by this project?

**Comment by bonifaido** [comment]
Really good question! @srenatus @JoelSpeed do you know if the chart in the community repo "belongs" to us?

**Comment by srenatus** [comment]
🏓@whereisaaron https://github.com/dexidp/dex/issues/1192

**Comment by jvanzyl** [comment]
It's definitely a strange default pointing to some random trading site. Their tag line is "Building an excellent decentralized exchange." which has nothing to do with DEX here, and probably would be pretty bad to send off any sensitive information there. It would be better if the chart defaulted to nothing.

**Comment by JoelSpeed** [comment]
We should try and fix this really, dex.io is nothing to do with us

Should just be a case of changing [this line](https://github.com/helm/charts/blob/65f1f381e293974b25e0903a45f395892f7bda7f/stable/dex/values.yaml#L165) to something like `https://dex.example.com:8443`?

**Comment by sagikazarmark** [comment]
I have plans to write a new helm chart and host it in the Dex organization, because what's in the community stable repo is really just awful.

Till then, I submitted helm/charts#20955

**Comment by sagikazarmark** [comment]
Fixed in the chart. Also requested to be a maintainer of the chart.
