### ISSUE TITLE
Revisit vendoring

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/dex#1597]
As far as I can tell, neither the current build process nor the docker build use the vendored dependencies.

While vendoring has certain advantages, it definitely has some disadvantages too and if it's not used at all I question its validity. (Yeah, I'm generally against vendoring).

**Comment by sagikazarmark** [comment]
#1596 is an example why vendoring is a pain.

**Comment by JoelSpeed** [comment]
+1 I'm also not a fan of vendoring and don't really see much value added here

**Comment by sagikazarmark** [comment]
Let's get rid of it then. PR incoming.
