### ISSUE TITLE
api: add call to update a client

### ISSUE THREAD

**Issue by bobbyrullo** [dexidp/dex#16]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Tuesday Jan 13, 2015 at 02:22 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/177_

---

allow clients to regenerate their own secret

**Comment by agentgonzo** [comment]
This would be very handy. At the moment, we have to delete/recreate a client if we want to change any of the redirectURIs for a client, which leaves a small window for login failures.
