### ISSUE TITLE
Question: How to modify sub filed in token?

### ISSUE THREAD

**Issue by gitwangdi** [dexidp/dex#1614]
I am going to combined istio authorization and dex authentication. 
Istio authorization policy uses iss/sub to recognize a user. 
To simplify the iss/sub, I attend to use email as token's sub field.
How can i do that?

**Comment by nabokihms** [comment]
According to the oidc specification, the sub claim provides a unique id for the user. As federative oidc provider dex can connect more than one authentication provider to itself. 

Now dex uses an encoded combination of authentication provider id and user id (which can be presented as email address) to accurately determine a user. Changing it will break entire logic.

I think you can change the istio default behavior using the docs https://istio.io/docs/reference/config/policy-and-telemetry/templates/authorization/ to use information from different claims (email claim, for example).
