### ISSUE TITLE
missing ./scripts/slapd.sh

### ISSUE THREAD

**Issue by bsctl** [dexidp/dex#1654]
I would follow the [LDAP tutorial](https://github.com/dexidp/dex/blob/master/Documentation/connectors/ldap.md) but the script `./scripts/slapd.sh` is missing.

**Comment by sagikazarmark** [comment]
@bsctl the documentation is a bit outdated. I'll try to update it when I get the time.

**Comment by vishal-swarankar-sdl** [comment]
@sagikazarmark  can you please update the doc or share the slapd.sh with us?

**Comment by vishal-swarankar-sdl** [comment]
@bsctl were you able to setup stuff using LDAP tutorial?

**Comment by prashanthc** [comment]
@sagikazarmark  Does the slapd.sh script still works? I installed the slapd and ldap-utils and tried to execute the script. It fails saying permission denied on /temp/temp.* folder which gets created while running the script.

**Comment by sagikazarmark** [comment]
slapd.sh has been removed because it was primarily used for automated testing.

Ideally, the LDAP example should use Docker (Compose) and I planned to rewrite the documentation, but I didn't have the time so far. (PRs are welcome 🙂 )

**Comment by tolson-vkn** [comment]
@sagikazarmark I was thinking about updating the docs for the LDAP tutorial this weekend. But wanted to get your thoughts on two was of doing it.
1. A docker-compose file that has both `osixia/openldap`, and `dexidp/dex`
2. Assume the user builds and runs dex locally and run `osixia/openldap` in a docker container 

Number 2 feels more like how the slapd script used to work and assuming the user builds it makes it work better in conjunction with [`getting-started.md`](https://github.com/dexidp/dex/blob/master/Documentation/getting-started.md). However it's less user friendly with someone who just wants to see how dex works.

I'm happy to do either option.

**Comment by heidemn-faro** [comment]
If anybody else is still looking for the old version of the script:

* Here it is: https://github.com/dexidp/dex/blob/bb2733fbdd4b4911eea52c90b8a92b392f7ca898/scripts/slapd.sh
* It was deleted in this commit: https://github.com/dexidp/dex/commit/26061f9558f3011bea53ef5a5bb02ac669d612e0

**Comment by heidemn-faro** [comment]
I've added the script again, and adapted it to run [OpenLDAP in Docker](https://hub.docker.com/r/osixia/openldap/).
https://github.com/dexidp/dex/pull/1762
