### ISSUE TITLE
Question: there's no local connector anymore?

### ISSUE THREAD

**Issue by ffd2subroutine** [dexidp/dex#1665]
I thought there would be a local connector that would allow users to signup/signin with username and password, has that been removed from dex?

**Comment by PeopleRange** [comment]
You can still use the local connector but Dex does not support user management features eg registration, resets etc you would have to implement these your self.

**Comment by aep** [comment]
that seems confusing because https://github.com/ory/hydra redirects to dex as an example of a complete idp.

**Comment by nabokihms** [comment]
Closing the issue because the question seems answered.
