### ISSUE TITLE
Send the connector used to the client

### ISSUE THREAD

**Issue by ctxnop** [dexidp/dex#1666]
Hello,
I setup a dex service with multiple connectors (github, google, etc...) and I would like that my client application can know which connector the user used to login.
I can't find anything in the received token/data.

The only way I found is to patch dex like this:
```diff
diff --git a/server/handlers.go b/server/handlers.go
index 0f5b0d2..6934f88 100644
--- a/server/handlers.go
+++ b/server/handlers.go
@@ -676,6 +676,7 @@ func (s *Server) sendCodeResponse(w http.ResponseWriter, r *http.Request, authRe
                v.Set("access_token", accessToken)
                v.Set("token_type", "bearer")
                v.Set("state", authReq.State)
+               v.Set("connector", authReq.ConnectorID)
                if idToken != "" {
                        v.Set("id_token", idToken)
                        // The hybrid flow with only "code token" or "code id_token" doesn't return an
@@ -713,6 +714,7 @@ func (s *Server) sendCodeResponse(w http.ResponseWriter, r *http.Request, authRe
                q := u.Query()
                q.Set("code", code.ID)
                q.Set("state", authReq.State)
+               q.Set("connector", authReq.ConnectorID)
                u.RawQuery = q.Encode()
```
Is there a better way to achieve that? Without patching dex?
If not, can this patch be merged-in?

It may be improved by added a config key that enable this feature?

**Comment by nabokihms** [comment]
I understand it was two years ago, but every issue deserves an answer. 

You should request the `federated:id` scope. Dex will include the info about the used connector and the user ID from the end provider to the ID token.
https://dexidp.io/docs/custom-scopes-claims-clients/#scopes

The example of an ID token:
```json
{
  "iss": "http://127.0.0.1:5556/dex",
  "sub": "xxx",
  "aud": "example-app",
  "exp": 1646409985,
  "iat": 1646323585,
  "at_hash": "xxx",
  "email": "maksim@example.com",
  "email_verified": true,
  "name": "Maksim Nabokikh",
  "federated_claims": {
    "connector_id": "my-gitlab-connector",
    "user_id": "07fbf889-b77e-4d87-d7ba-4904baa381fe"
  }
}
```

I hope that it will help. If you still have questions, please open a new issue.

**Comment by ajh-** [comment]
> I understand it was two years ago, but every issue deserves an answer.
> 
> You should request the `federated:id` scope. Dex will include the info about the used connector and the user ID from the end provider to the ID token. https://dexidp.io/docs/custom-scopes-claims-clients/#scopes
> 
> The example of an ID token:
> 
> ```json
> {
>   "iss": "http://127.0.0.1:5556/dex",
>   "sub": "xxx",
>   "aud": "example-app",
>   "exp": 1646409985,
>   "iat": 1646323585,
>   "at_hash": "xxx",
>   "email": "maksim@example.com",
>   "email_verified": true,
>   "name": "Maksim Nabokikh",
>   "federated_claims": {
>     "connector_id": "my-gitlab-connector",
>     "user_id": "07fbf889-b77e-4d87-d7ba-4904baa381fe"
>   }
> }
> ```
> 
> I hope that it will help. If you still have questions, please open a new issue.

@nabokihms For a simple Dex setup, where would you include `federated:id` scope? Something like below?

```
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: ...
    clientSecret ...
    redirectURI: ...
    scopes:
      - openid
      - profile
      - email
      - federated:id
```
Or would the `OAuth 2.0` connector be better suited?
