### ISSUE TITLE
Does dex handle session management?

### ISSUE THREAD

**Issue by kishansagathiya** [dexidp/dex#1677]
I am trying to check if a user is logged in, and if it is then who?

I did not find anything relevant going through docs and code. Also my browser did not show any session cookies by dex. 
I think, OpenID and OAuth 2.0 does not require to handle session management. 

Can you confirm if dex does it or not?

**Comment by bonifaido** [comment]
No, Dex doesn't do session management. It acts as an OIDC proxy frontend in from of different IdPs. State management has to be done in your application or in any other supporting applications.
