### ISSUE TITLE
Create Dex Kubernetes Slack Channel

### ISSUE THREAD

**Issue by kenperkins** [dexidp/dex#1682]
I propose creating a slack channel on the kubernetes slack; If there is agreement I will do two things:

1. Create the appropriate Pull Request on the [Kubernetes Community](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel)
2. Create a pull request on DexIdp documenting the slack channel and how to access it

I would propose using `#dex` over `#dexidp`, but I'd like to get the feedback of other maintainers and contributors.

@bonifaido @srenatus @JoelSpeed (anyone else?)

**Comment by JoelSpeed** [comment]
My concern is that Dex may not be considered close enough to the Kubernetes project for the K8s community to consider this a reasonable channel request. Could try the Gophers slack as an alternative if that fails.

Having a slack channel in general seems like a reasonable idea to me though, +1

**Comment by kenperkins** [comment]
I think it's fair to say that Dex, to a degree, is orthogonal to Kubernetes, but I would love to figure out a solution. A quick glance at the Gophers slack says it can be done without a code change. Maybe we should try there and feel it out.

Thanks for that suggestion @JoelSpeed

**Comment by JoelSpeed** [comment]
I would suggest asking in the K8s slack #slack-admins channel to see what they think if you think the K8s slack would be a better home

**Comment by kenperkins** [comment]
I got a receptive request from the Slack Admins on K8s. I think we should go forward with K8s.

**Comment by JoelSpeed** [comment]
Ack sounds good to me

**Comment by bonifaido** [comment]
I also vote for the k8s slack! 👍

**Comment by kenperkins** [comment]
PR https://github.com/kubernetes/community/pull/4690 has been merged; waiting on automation to actually create it.

**Comment by kenperkins** [comment]
FYI it turns out there was a uniqueness constraint, so we will be #dexidp instead.

**Comment by kenperkins** [comment]
DexIdp is created, I'll author a PR for here next.

**Comment by kenperkins** [comment]
It goes without saying, I'll be in #dexidp going forward.
