### ISSUE TITLE
Refresh Token Expiry?

### ISSUE THREAD

**Issue by geofffranks** [dexidp/dex#1685]
Is it possible to configure how long a refresh token is valid for? We're looking to make use of access token validity to ensure that ldap groups get synced up every 5 minutes or so, but then rely on refresh token expiry to force users to log in again every X hours. We saw a github issue from a few years ago discussing a script that would periodically revoke refresh tokens based on their age, but wondering if there's anything built-in to support this now.

Would this even work for our use case, or do we need to force a new refresh token to get group-membership info to be propagated into the token itself? Would that change between backends (LDAP vs SAML)? Is there a way to disable refresh tokens altogether?

**Comment by jseadragon** [comment]
Hey @geofffranks I had a similar question. Check out my reply: https://github.com/dexidp/dex/issues/1203#issuecomment-613151280

**Comment by torgeros** [comment]
> Is there a way to disable refresh tokens altogether?

For anyone with this question:
It is possible to disable refresh tokens completely by removing `refresh_token` from `oauth2.grantTypes` in config.yaml.
