### ISSUE TITLE
pass in redirecturl for github connector

### ISSUE THREAD

**Issue by sockmister** [dexidp/dex#1699]
Github's oauth flow accepts a `redirect_uri` field that would allow the field to override the callback URL set in Githbub itself (subjected to some restrictions) https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls. 

However, it appears that the connector does not perform the `Exchange` with the `RedirectURL` set https://github.com/dexidp/dex/blob/0a85a97ba9d85fa0de8542a68f1edbc53ed77c25/connector/github/github.go#L179-L184
even though the connector itself possesses such a field https://github.com/dexidp/dex/blob/0a85a97ba9d85fa0de8542a68f1edbc53ed77c25/connector/github/github.go#L132-L133

I tested a build locally where the field gets passed in in the `oauth2Config` method and it appears to work well with Github.

I hope to discuss and consider merging such a change. Thank you.

**Comment by sockmister** [comment]
PR was merged :D

**Comment by mervynzhang** [comment]
Hi,

This change break kubeflow default settings. kubeflow use kubernetes internal svc in dex as issuer, such as 
```
issuer: http://dex.auth.svc.cluster.local:5556/dex
```
If the github redirectURI configured as http://dex.auth.svc.cluster.local:5556/dex/callback, github will redirect to this url and we cannot access it.

If redirectURI configured public url, got following error
```
level=error msg="Connector \"github\" returned error when creating callback: expected callback URL \"http://dex.auth.svc.cluster.local:5556/dex/callback\" did not match the URL in the config 
```
dex could leave out redirectURI or do not compare it with issuer in internal usage?

https://docs.github.com/en/developers/apps/managing-oauth-apps/troubleshooting-authorization-request-errors#redirect-uri-mismatch

Thanks
