### ISSUE TITLE
Create an official Helm chart

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/dex#1709]
Dex's "official" helm chart in the [helm/charts stable repo](https://github.com/helm/charts/tree/master/stable/dex) is far from perfect, not to mention that the official Helm chart repo will be deprecated by the end of the year.

We should create a new, official chart for Dex.

The only question is where we should host it:

- We could set up a chartmuseum instance somewhere and host it under `charts.dexidp.org` (we need that domain BTW)
- We could host a static chart repository in this repo using [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action)
- We could host the chart in [Banzai Cloud's chart repo](https://github.com/banzaicloud/banzai-charts)

WDYT?

/cc @bonifaido @srenatus

**Comment by srenatus** [comment]
I'd go with the simplest option, and I suppose that's the second one -- static chart repo? 🤔

**Comment by sagikazarmark** [comment]
I guess it is, still, I would consider having a domain of our own, just in case we decide to move it away from github.

Anyway, I will give the releaser action a try to see how it works.

**Comment by srenatus** [comment]
I'd be curious what others say, too. Also, when it comes to having some infrastructure at our disposal, I wonder if this is where CNCF could come in. But I haven't tracked the status of that process, tbh.

Also, we're currently not using any helm charts, so my opinion shouldn't weight much here 😅

**Comment by sagikazarmark** [comment]
> I wonder if this is where CNCF could come in

This issue came up right before VMware approached us with joining CNCF which is why I've put this on hold, but the need for a better chart just came up again, so I decided to at least open an issue and start a discussion.

**Comment by srenatus** [comment]
Sounds alright, better to act now. It's probably of use to a many users :+1:

**Comment by vi7** [comment]
Hi folks, have you considered distribution of the Dex via `kustomize`? IMHO that can be an option too, kustomize has certain benefits over the helm chart
Just as an example - MetalLB follows that approach: https://metallb.universe.tf/installation/#installation-with-kustomize  
I believe MetalLB "official" chart is mostly abandoned atm

**Comment by sagikazarmark** [comment]
I don't think the two aren't mutually exclusive, the question is whether we have bandwidth for both. Feel free to open a separate issue for Kustomize support.

**Comment by asetty** [comment]
Any update on this? I'm needing to update my dex config and make a couple enhancements to chart I've vendored locally in the past from the old `stable` helm repo.

I think it makes sense as a first step it makes sense to at least add the helm chart to this repo under a folder such as `helm`, or `assets/helm`. That way there is SOME official chart and updates to the chart can be made in the same PR as relevant code changes when applicable. 

The chart releaser action or something like this could also be added, then in a future iteration the chart could maybe be hosted  charts.dexidp.org  / chartmuseum.

In the meantime, I'm going to make changes to the chart locally to satisfy my requirements and then will try to push a PR  to this repo to help drive this forward.

**Comment by postmaxin** [comment]
The deployment of Dex is super super simple. There is nothing special or unique about it that requires an extended (helm) configuration.

At my company, we have a standard helm chart that we use for our 100+ microservices. We were able to use that chart to deploy Dex and there were no complications at all, literally just added a few lines to a values.yaml file.

**Comment by asetty** [comment]
@postmaxin I see where you're coming from. It really is just a matter of using the correct image and providing a config file, the rest is boilerplate.

I'd like to hear other's thoughts on this. Is it worth maintaining a helm chart in this repo? Maybe at least some documentation about deployment and/or an example manifest could be added. I often find this useful to lower the barrier to entry if I want to quickly test some open source software. (but maybe also defining a few standard, simple charts to use at my company would be useful... :))

**Comment by sagikazarmark** [comment]
Sorry, I haven't been able to work on this so far. I'll try to find some time in the near future. We have some practice with running Dex in Kubernetes and it's not that simple which is why it's a little bit more than a `helm create`.

I've created a helm chart repo, we'll push the repo there once it's ready: https://github.com/dexidp/helm-charts

**Comment by NahaliY** [comment]
Hi @sagikazarmark , I see that the new official Helm chart is not yet completed in this Repo : [https://github.com/dexidp/helm-charts](https://github.com/dexidp/helm-charts). Is there a new official source for dex Helm chart ?  Or it's under development ? 
Thank's in advance for your feedback ;) .

**Comment by sagikazarmark** [comment]
@NahaliY please follow dexidp/helm-charts#2 as well. It tracks the current blockers for releasing a helm chart. It's under development.

**Comment by sagikazarmark** [comment]
Hey folks,

Please take a look at dexidp/helm-charts#3, give it a try and share some feedback. Thanks!

**Comment by sagikazarmark** [comment]
The first version is available at https://charts.dexidp.io/
