### ISSUE TITLE
Issue with using the client package v2 version in go modules project

### ISSUE THREAD

**Issue by ccojocar** [dexidp/dex#1710]
I am trying to use client package latest v2 version in a go modules project but there is an error:

```
go get -u github.com/dexidp/dex@v2.24.0
go get github.com/dexidp/dex@v2.24.0: github.com/dexidp/dex@v2.24.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I think the v2 version is not properly handled following these recommendations:
https://blog.golang.org/v2-go-modules

**Comment by sagikazarmark** [comment]
This has been addressed in the PR. There is also a separate API package which is the only reasonable (and supported) explanation for why someone would want to import Dex.

See https://github.com/dexidp/dex/releases/tag/api%2Fv2.0.0
