### ISSUE TITLE
quay.io/dexidp/dex:v2.24.0 is DOWN!

### ISSUE THREAD

**Issue by thesuperzapper** [dexidp/dex#1716]
Currently `quay.io/dexidp/dex:v2.24.0` is returning a 500 Internal service error!

Example:
```bash
docker run -it quay.io/dexidp/dex:v2.24.0 /bin/bash
# docker: Error response from daemon: Get https://quay.io/v2/dexidp/dex/manifests/v2.24.0: received unexpected HTTP status: 500 Internal Server Error.
```

Aside fixing this issue, we should use this as a good case to migrate to the official docker-hub, so we can prevent this in the future.

**Comment by thesuperzapper** [comment]
@rithujohn191 @srenatus @JoelSpeed @bonifaido @sagikazarmark

**Comment by JoelSpeed** [comment]
Quay are aware of the issue and are investigating it presently. https://status.quay.io

Docker Hub also has outages so migrating wouldn't prevent such issues.

One option would be to maintain mirrors, but this is an additional overhead that I think is likely not that worth it 99% of the time.

**Comment by sagikazarmark** [comment]
> One option would be to maintain mirrors, but this is an additional overhead that I think is likely not that worth it 99% of the time.

Well, if we build container images in the CI, we can easily push to multiple registries.

**Comment by sagikazarmark** [comment]
It looks like quay is back in readonly mode.
