### ISSUE TITLE
Accept/Modify Claims (ID-Token Payload) from Connector (ex. AzureAD) for example to small letters

### ISSUE THREAD

**Issue by VF-mbrauer** [dexidp/dex#1725]
If we get back the OAUTH reponse from AzureAD (Microsoft Connector) it can happen that the AD delivers the users E-Mail which we will use later on in Kubernetes RBAC (Rolebinding) to assign the user to a role, it with uppercase and lowercase letters.

That depends on the User who has configured the AzureAD User. So in case the name is for example
`Firstname.Lastname@example.com`  we need exact the match in the rolebinding with the Capital "F" and the Capital "L" in the name.

So we can't foreseen how the user has been added to AzureAD. So it would be good to have a kind of **.lowercase()** function that it doesn't matter if the letters are big or small.

**Comment by phenixblue** [comment]
I would also love to see this for the LDAP Connector. The same scenario applies when using the LDAP connector to bind to Active Directory.

**Comment by TheMeier** [comment]
https://dexidp.io/docs/connectors/microsoft/

> You can use the emailToLowercase (boolean) configuration option to streamline UPNs (user email) from Active Directory before putting them into an id token. Without this option, it can be tough to match the email claim because a client application doesn’t know whether an email address has been added with capital- or lowercase letters. For example, it is hard to bind Roles in Kubernetes using email as a user name (–oidc-username-claim=email flag) because user names are case sensitive.

**Comment by VF-mbrauer** [comment]
Hi @TheMeier, yes correct. I created the piece of code and put the PR in place to get it into the 2.28.0 release. So basically, solved the issue myself :-) 
We could mark this issue as `solved`
