### ISSUE TITLE
Make the API package a separate module

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/dex#1726]
The protobuf descriptors for Dex are currently available in the `api` package which people tend to import in their own application. Unfortunately, this can lead to a number of issues (large number of dependencies, conflicting dependencies, etc) which is why importing application code is usually not advised.

By making the aforementioned package a separate module, people can continue importing it, without importing the entire application at the same time.

This change would be backward compatible, with the exception of multiple modules importing different versions of Dex. Go get would fail in that case. (Microsoft did the same with autorest, it took some time for the community to get used to it)

@bonifaido @srenatus what do you think?

**Comment by srenatus** [comment]
We might some day want a v2 api, but I don't think that this matters for what's discussed here. Sounds good to me!

**Comment by sagikazarmark** [comment]
Technically, I guess this is the v2 API. We can always add a v2/v3 under the same module.
