### ISSUE TITLE
case sensitive checking for saml attributes.

### ISSUE THREAD

**Issue by ShramikGajlekar** [dexidp/dex#1729]
The current group assertion check is case sensitive and it seems a lot restrictive. If Okta sends `GroupsAttr` as groups and the connector has it `Groups` even if the parsed saml response may show groups the idenity object is never populated with the correct groups.

Relaxation is probably needed with this strict attribute checking.

**Comment by sagikazarmark** [comment]
Correct me if I'm wrong, but AFAIK attribute names are supposed to be case sensitive.
