### ISSUE TITLE
Unable to skip the "grant access" page

### ISSUE THREAD

**Issue by Keerthana2496** [dexidp/dex#1733]
I tried this below solution, still i am getting the grant access page

_Originally posted by @srenatus in https://github.com/dexidp/dex/issues/1172#issuecomment-357876265_

**Comment by jenting** [comment]
Could you please provide your dex version & dex configuration? Thanks.

**Comment by nabokihms** [comment]
I tested the feature, and it works as expected. If the problem is still relevant, please open a separate issue or discussion to track it.
