### ISSUE TITLE
Move examples to a separate repo or module

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/dex#1740]
Make sure that examples does not pull in extra dependencies into the project.

**Comment by sagikazarmark** [comment]
@JoelSpeed @bonifaido what do you think would be better? A separate repository or separate modules in the main repository.

I'm leaning towards one of those options, but wanted to hear your opinion as well.

**Comment by JoelSpeed** [comment]
I don't see any reason not to make them separate modules, would be easier for people to find at least. A second repo would be harder to get started with them right?

**Comment by sagikazarmark** [comment]
Yes, separate modules are easier to find and easier to keep updated, but separate repos are easier to clone and we can avoid the module hell in the main repo.

I'd start with separate module though (if it works). We can always move stuff to separate repo if necessary.

**Comment by bonifaido** [comment]
I'm a fan of the "same repo, different module" approach too.
