### ISSUE TITLE
Enable DCO as part of CNCF onboarding

### ISSUE THREAD

**Issue by caniszczyk** [dexidp/dex#1753]
Per the CNCF IP Policy, projects must use DCO

I installed and enabled it on your repo: https://github.com/organizations/dexidp/settings/installations/10223994

You may want to give devs a heads up they will need to sign off commits via 'git commit -s' moving forward

**Comment by sagikazarmark** [comment]
Thanks!

We should probably have/update a contribution guide, will include it there.

**Comment by JoelSpeed** [comment]
How does the DCO plugin handle multiple authors on a commit? Or commit squashing when we merge branches? Is there any behaviour that we might need to change when reviewing or merging once this is running?

**Comment by nabokihms** [comment]
@sagikazarmark @justaugustus 
We could enable the new GitHub feature to avoid signing web commits manually. See for more info https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/

**Comment by caniszczyk** [comment]
CNCF can enable this setting as we will make it default for all projects in the future anyway

So consider it done. If you wanted to remove it for some reason you can but I'd advise no :)

**Comment by sagikazarmark** [comment]
Configured it for the dex project.

**Comment by sagikazarmark** [comment]
I believe this is done.
