### ISSUE TITLE
Dex not creating refreshtoken resources in k8s storage

### ISSUE THREAD

**Issue by jarrettprosser** [dexidp/dex#1755]
I've got Dex configured to use Kubernetes storage. I'm using a single LDAP connector. A React client implementing oidc-client.js is requesting the response type `id_token token` and scopes `openid profile email offline_access`. The login works fine. When the token times out, the client tries to perform a silent refresh but after several attempts times out and logs the user off.

From the documentation I understand that a client request with the `offline_access` scope should be provided a refresh token. When a user is logged in there are no RefreshToken custom resources created in k8s. An OfflineSession resource is created on first login with only `metadata` and `userID` fields present - no `ConnID` or `Refresh` values. Am I looking in the wrong place or missing some configuration I need to get the refresh tokens running?

Dex version: 2.23.0
Kubernetes version: 1.16.3

Thanks!

**Comment by jenting** [comment]
Have you provide the “idp-certificate-authority “ or “idp-certificate-authority-data” to the oido-client.js?

**Comment by jarrettprosser** [comment]
I believe oidc-client.js doesn't require “idp-certificate-authority “ or “idp-certificate-authority-data” values. There is no mention of those or similar parameters in the [documentation](https://github.com/IdentityModel/oidc-client-js/wiki).

**Comment by jarrettprosser** [comment]
I've looked into this more and realise now that I am requesting the response types `id_token token` and so will not get a refresh token, per the OAUth 2.0 spec. I'm unable to use the `code` flow because we are operating in security environments which require the `code` flow to implement PKCE, which I see is a [WIP](https://github.com/dexidp/dex/pull/1652). 

I suspect the timeout behaviour I am seeing is because the oidc-client.js library is attempting to perform the [silent refresh](https://www.scottbrady91.com/OpenID-Connect/Silent-Refresh-Refreshing-Access-Tokens-when-using-the-Implicit-Flow) process, which I think Dex does not currently support according to the comments on [this issue](https://github.com/dexidp/dex/issues/990). 

I'll look into what alternatives are available to me - thanks.
