### ISSUE TITLE
Question: How much does Dex store in Kubernetes CRDs and how often?

### ISSUE THREAD

**Issue by tomqwpl** [dexidp/dex#1759]
I see that there is support for Dex using kubernetes CRDs for its storage requirements. I can see that setting it up us super simple.
What I'm not clear about is how much Dex stores there and how often.
If each authentication request causes something to be stored in a CRD, does that have the potential to overwhelm the kubernetes etcd servers? How long do those records stay there? 

Are there any guidelines anywhere for what the best storage solution is in a kubernetes environment?

**Comment by tkleczek** [comment]
For each started authentication (i.e. user visiting initial "Choose connector" page) an AuthRequest object is created in storage. Their expiry is configurable via config, default: 24h.
Then upon successful user login an AuthCode object is created. It's expiry is 30 mins.
Other objects that are created are OfflineSessions and RefreshTokens. They are long lived (in fact they never expire unless revoked) but there are at most one of those for unique (user, connector, client) triple.

**Comment by tomqwpl** [comment]
OK, thanks. Very helpful in terms of understanding the implications of using kubernetes storage.
