### ISSUE TITLE
Create a dex website

### ISSUE THREAD

**Issue by justaugustus** [dexidp/dex#1761]
We need a website.
Hugo + Netlify has been the suggested path from multiple people, including CNCF staff (thanks @celestehorgan), so let's proceed down that path.

I've created https://github.com/dexidp/website, which is templated from the https://github.com/cncf/hugo-netlify-starter template project, but it's not wired up properly yet.

**Comment by celestehorgan** [comment]
Welp. That didn't work. @justaugustus, @hackabletype is gonna take this on, please unassign yourself and assign him!

**Comment by hackabletype** [comment]
Hello @justaugustus, I've just been brought on at the CNCF and would like to work on this.

**Comment by hackabletype** [comment]
I see there is a lot of documentation already written in https://github.com/dexidp/dex#documentation, and I was thinking as a first step that I'd migrate it over to the https://github.com/dexidp/website repo, then start wiring the Netlify stuff.

Is this Documentation up to date? Does it need revision before it's brought out of the main repo and put into the website one?

**Comment by JoelSpeed** [comment]
> Is this Documentation up to date? Does it need revision before it's brought out of the main repo and put into the website one?

Would it be an issue to update it once it's migrated? I don't think it being out of date needs to be a blocker for your work (if it is even out of date)

**Comment by sagikazarmark** [comment]
Thanks a lot for helping out @hackabletype

The documentation is mostly up-to-date, but I think it might make sense to find a better structure for it. Right now everything is under a single "group", but having a more organized structure (let's say for connectors, use cases, how-tos) would be nice.

But I'm not sure if we can or should do it now. Instead, I would start with a single landing page and migrate the documentation in small steps. WDYT?

**Comment by hackabletype** [comment]
@JoelSpeed, you're right, once it's in the other location it shouldn't be a problem to update it there, would just need to let people know of the migration when it happens so they know where things are.

**Comment by hackabletype** [comment]
@sagikazarmark, you're welcome, I'm happy to do it! I think that we should probably do the move, then restructure it and organize it there. Once everything is migrated, we can create issues and a project board on that repo to keep things organized. I think moving it in a chunk would probably be easier because it's all interlinked (but contained in one folder).

**Comment by sagikazarmark** [comment]
Sounds good to me!

**Comment by hackabletype** [comment]
I think a lot of the progress of this issue will be shown in the [dexidp/website](https://github.com/dexidp/website) repo's [issues page](https://github.com/dexidp/website/issues).

**Comment by JoelSpeed** [comment]
I support moving it in one go, will be easier to get a clean cutover. We can leave a readme in the old docs location that points to where the new ones will be while we are setting them up and reorganising so people can still find them

Thanks for volunteering btw! Looking forward to seeing what you come up with 😄

**Comment by hackabletype** [comment]
PR for the first part of the migration over on the dexidp/website repo: https://github.com/dexidp/website/pull/8

**Comment by hackabletype** [comment]
PR for the removal part of this migration: https://github.com/dexidp/dex/pull/1809

**Comment by nate-double-u** [comment]
@justaugustus @sagikazarmark this issue may be finished now with https://dexidp.io up :)

**Comment by sagikazarmark** [comment]
Yes, thanks a lot!
