### ISSUE TITLE
How to setup debug on Local Setup?

### ISSUE THREAD

**Issue by ram-coderr** [dexidp/dex#1775]
I'm new to Golang & Dex. I'm looking for guidance on Debuging Local Setup.
I started the Dex and the API responding. Looking guidance on how to start Dex on debug mode in my local machine?

Steps followed to start the dex:-

Method 1: 
./bin/dex serve examples/config-dev.yaml

Method 2: 
docker-compose build
docker-compose up

* Connector github.com & Storage: Postgres

Issue & Question:-
1) I made a static content changes on code, but its not reflecting. Example "Invalid UserName & Password" to "Invalid User & Pass" -> No change on output. I believe it's reading from binary "bin/dex". How can I point/start on to non-binary?
 
* I'm using Visual Studio Code, how can I setup debugger for dex?

Any suggestion helps?

**Comment by tkleczek** [comment]
Try the following configuration in your launch.json file:

```
    "configurations": [
        {
            "name": "Dex",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/dex",
            "args": [
                "serve",
                "${workspaceFolder}/examples/config-dev.yaml"
            ],
            "cwd": "${workspaceFolder}"
        }
    ]
```

**Comment by sagikazarmark** [comment]
In addition to the above snippet, there is a quite extensive documentation in the extension repo on how to use VS Code for debugging:

https://github.com/golang/vscode-go/blob/master/docs/debugging.md
