### ISSUE TITLE
Support secretEnv in oauth2client k8s CR

### ISSUE THREAD

**Issue by snuggie12** [dexidp/dex#1786]
This feature exists in static clients but it'd be nice if it worked for the `oauth2client` resource as well.

Alternatively using the `valueFrom.secretKeyRef` pattern would be just as useful.

**Comment by nabokihms** [comment]
Starting from the [v2.28.0](https://github.com/dexidp/dex/releases/tag/v2.28.0) Dex has a gomplate in the docker image to render the config before container starting.

Using gomplate users ca inject any secrets from env variables.

I'm going to close this issue. Feel free to reopen it if you need an help.
