### ISSUE TITLE
Add IP addresses of clients to log messages

### ISSUE THREAD

**Issue by nabokihms** [dexidp/dex#1788]
Sometimes it is helpful to see users' IP addresses in successful or failed authorization request log entries. This behavior can be achieved by using simple nginx in front of dex and looking into nginx logs, but it would be more convenient and simpler to see addresses in dex logs.

Maybe it's better to add this feature only for debug logging mode.
For example:
```
{"level":"info", "client_address":"192.168.0.1", "msg":"login successful: connector \"what-is-it\", username=\"Maksim Nabokikh\", preferred_username=\"maksim.nabokikh\", email=\"maksim.nabokikh@example.com\", groups=[]","time":"2020-08-31T14:41:31Z"}
```

**Comment by sagikazarmark** [comment]
I'd definitely make that optional.....because GDPR.

**Comment by sagikazarmark** [comment]
Note: need to be able to set trusted proxies to properly detect client IPs.

**Comment by nabokihms** [comment]
closed by https://github.com/dexidp/dex/pull/3661
