### ISSUE TITLE
Dex error-handling is not RFC-compliant

### ISSUE THREAD

**Issue by tkleczek** [dexidp/dex#1796]
According to RFC (https://tools.ietf.org/html/rfc6749#section-4.1.2.1) most errors from Authorization Code Grant part of the authentication flow should be reported back to the client via HTTP redirect with additional query parameters set, e.g:

```
HTTP/1.1 302 Found
   Location: https://client.example.com/cb?error=access_denied&state=xyz
```

Instead, most error paths in Server's methods handleAuthorization, handleConnectorLogin, handleConnectorCallback and handleApproval (which all handle code grant) serve dex error page template in case of errors.
Moreover, in at least once instance a bare json is returned via server.tokenErrHelper method.

Also: when handling /token endpoint RFC says that "invalid_grant" error should be returned if code parameter is invalid/expired, (https://tools.ietf.org/html/rfc6749#section-5.2) whereas Dex returns "invalid_request in this case.

**Comment by IlyushaZ** [comment]
I'm not sure if this one is completed. When using recent versions of dex, `invalid_request` is returned when refresh token is expired.
