### ISSUE TITLE
dex response url stripping query params

### ISSUE THREAD

**Issue by vinayus** [dexidp/dex#1798]
i have a weird issue. i use oauth2_proxy and dex for sake of my SSO.
i'm trying to hit this url: **https://app.172.16.21.149.nip.io:32443/rest/ui/bulk/compliance/report/download?name=report5**
which should ideally download a report of that name based on session or goto login screen if session is missing.
when session is fine, it works fine.

but when session is new, somehow the query params are skipped in url.. so it auth url ends up..
**_https://app.172.16.21.149.nip.io:32100/auth?acr_values=&approval_prompt=force&client_id=haproxy&redirect_uri=https%3A%2F%2Fapp.172.16.21.149.nip.io%3A32443%2Foauth2%2Fcallback&response_type=code&scope=groups+openid+profile+email&state=74a4b71610173b667c97f939663a8e89%3A%2Frest%2Fui%2Fbulk%2Fcompliance%2Freport%2Fdownload_**

and after auth, we end up with invalid url like this..
**_https://app.172.16.21.149.nip.io:32443/rest/ui/bulk/compliance/report/download_**
so here missing part is _?name=report5_

can someone help me whether this needs special handling anywhere?

**Comment by UmangGupta0409** [comment]
Facing same issue, let me know once u find anything conclusive

**Comment by vinayus** [comment]
Turns out its a bug in oauth2_proxy and not dex.
https://github.com/oauth2-proxy/oauth2-proxy/issues/695

Updating the image in oauth2_proxy fixed the issue for me.
