### ISSUE TITLE
"web" directory copied incorrectly in Dockerfile

### ISSUE THREAD

**Issue by al45tair** [dexidp/dex#1820]
The Dockerfile was changed from

    COPY web /web

To

    COPY web .

Unfortunately, the latter copies *the contents* of the directory "web" to the current directory. i.e. the final Docker image ends up looking like this:

    / $ ls
    bin        home       mnt        root       srv        templates  usr
    dev        lib        opt        run        static     themes     var
    etc        media      proc       sbin       sys        tmp

instead of like this:

    / $ ls /
    bin    etc    lib    mnt    proc   run    srv    tmp    var
    dev    home   media  opt    root   sbin   sys    usr    web

The upshot is that when you try to use the Docker image, it terminates with

    failed to initialize server: server: failed to load web static: load web dir: directory "./web" does not exist

**Comment by nabokihms** [comment]
Closed in https://github.com/dexidp/dex/pull/1821
