### ISSUE TITLE
"select another login method" link causes database error

### ISSUE THREAD

**Issue by tomqwpl** [dexidp/dex#1849]
If you select a login method that requires the password entry dialog to be displayed, there's a link at the bottom "select another login method". If you click on this, then select a different login method you get an error screen with "database error".
In the Dex log there is "connector is already set for this auth request".
So it looks like Dex doesn't actually support changing to a different login method.

**Comment by al45tair** [comment]
This is a symptom of the problem mentioned in #646, namely that the authorisation request is persisted too early.
