### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by caniszczyk** [dexidp/dex#1867]
Dex needs a security disclosure process :)

**Comment by sagikazarmark** [comment]
@caniszczyk sure!

For that, we'll need a security email address though (ie. security@dexidp.io ?). I think @justaugustus mentioned setting up GoogleApps, but I guess we could also use the mailing list? Can you help us with that?

Are there any CNCF guidelines that we should follow?

**Comment by caniszczyk** [comment]
I'd recommend looking at some examples:

https://github.com/containerd/project/blob/master/SECURITY.md
https://github.com/coredns/coredns/blob/master/.github/SECURITY.md

For the security alias, we can set something up on groups.io, just file a servicedesk ticket for that

**Comment by razigarbie** [comment]
Hi guys,

Whats your current preferred way to report security vulnerabilities? (low severity)

**Comment by nabokihms** [comment]
Related to https://github.com/dexidp/dex/issues/1617
