### ISSUE TITLE
Ldap group search with FreeIPA does not work

### ISSUE THREAD

**Issue by ieugen** [dexidp/dex#1873]
**Expected behavior (what you expected to happen)**:

Login with ldap / FreeIPA and have groups added to the token / found.

**Actual behavior (what actually happened)**:

Login works but no groups are returned by the query. 

**Steps to reproduce**:
1. FreeIPA setup
2. configure dex with ipa back-end
3. Try to login

**Environment**:
- Dex version:  ghcr.io/dexidp/dex:v2.26.0
- Storage type: kubernetes
- Installation type (official docker image, helm chart, etc.): https://artifacthub.io/packages/helm/gabibbo97/dex  dex 3.8.0

**Anything else we should know?**:

I have checked the other issues related to LDAP: 

https://github.com/dexidp/dex/issues/1787
https://github.com/dexidp/dex/issues/1190
And other issues.
Also tried with userMatch.

Running the query via ldapsearch works and returns the groups - .

```
ldapsearch -b "cn=groups,cn=accounts,dc=example,dc=com" "(|(objectClass=group)(member=uid=my-user-name,cn=users,cn=accounts,dc=example,dc=com))"

# sample_group, groups, accounts, example.com
dn: cn=sample_group,cn=groups,cn=accounts,dc=example,dc=com
cn: sample_group
description: REDACTED
objectClass: top
objectClass: groupofnames
objectClass: nestedgroup
objectClass: ipausergroup
objectClass: ipaobject
ipaUniqueID: 4936d5bc-2ffe-11eb-9131-96000075af78
member: cn=otehr_grou,cn=groups,cn=accounts,dc=example,dc=com
member: uid=aaaaa,cn=users,cn=accounts,dc=example,dc=com
member: uid=bbbb,cn=users,cn=accounts,dc=example,dc=com


# search result
search: 4
result: 0 Success

# numResponses: 12
# numEntries: 11
```

<details><summary>Configuration</summary><br><pre>
      connectors:
      - config:
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=example,dc=com
            filter: (objectClass=group)
            groupAttr: member
            userAttr: DN
            nameAttr: cn
          userSearch:
            baseDN: cn=users,cn=accounts,dc=example,dc=com
            emailAttr: mail
            filter: (objectClass=posixAccount)
            idAttr: uid
            nameAttr: gecos
            username: uid
          usernamePrompt: User name
        id: ldap
        name: Example Corp
        type: ldap
</pre></details>

<details><summary>Logs</summary><br><pre>

{"level":"info","msg":"listening (http) on 0.0.0.0:8080","time":"2020-11-26T17:17:55Z"}
{"level":"info","msg":"performing ldap search cn=users,cn=accounts,dc=example,dc=com sub (\u0026(objectClass=posixAccount)(uid=my-user-name))","time":"2020-11-26T17:18:59Z"}
{"level":"info","msg":"username \"my-user-name\" mapped to entry uid=my-user-name,cn=users,cn=accounts,dc=example,dc=com","time":"2020-11-26T17:18:59Z"}
{"level":"info","msg":"performing ldap search cn=groups,cn=accounts,dc=example,dc=com sub (\u0026(objectClass=group)(member=uid=my-user-name,cn=users,cn=accounts,dc=example,dc=com))","time":"2020-11-26T17:18:59Z"}
{"level":"error","msg":"ldap: groups search with filter \"(\u0026(objectClass=group)(member=uid=my-user-name,cn=users,cn=accounts,dc=example,dc=com))\" returned no groups","time":"2020-11-26T17:18:59Z"}
{"level":"info","msg":"login successful: connector \"ipa-libris-ldap\", username=\"Handsome Me\", preferred_username=\"\", email=\"my-user-name@example.com\", groups=[]","time":"2020-11-26T17:18:59Z"}
</pre></details>

**Comment by ieugen** [comment]
Managed to get it working after checking the source code and using this configuration:

```
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=example,dc=com
            filter: "(|(objectClass=posixGroup)(objectClass=groupOfNames))"
            userMatchers:
             - groupAttr: member
               userAttr: DN
            nameAttr: cn
```

**Comment by anthr76** [comment]
I've tried your configuration, but I'm getting back blank groups. Can you verify it's correct?

**Comment by vikas-prabhakar** [comment]
@ieugen I am also facing same issue, i tried with suggested changes but it's not working
