### ISSUE TITLE
Endpoint to fetch a list of connectors

### ISSUE THREAD

**Issue by al45tair** [dexidp/dex#1875]
**Is your feature request related to a problem? Please describe.**
We're implementing a user registration flow, where a sysadmin sends an invitation, and we'd like a way to grab a list of the configured connectors from the running Dex instance. One of our developers tried fetching /dex/auth and scraping it, which (sort of) works except when there's only a single connector; in the latter case, we get a redirect and since this is happening in front-end code using XMLHttpRequest (under the covers), that ends in a 400 Bad Request.

**Describe the solution you'd like to see**
There should be a /connectors endpoint that responds with a JSON list of connectors. The type, id and name should be exposed in each case.

**Describe alternatives you've considered**
I did consider writing a separate server that reads the Dex config and generates what we need, but I think this is easiest to do within Dex and I don't see any obvious downside.

**Comment by sagikazarmark** [comment]
#1489 implements a connector list in the gRPC API which is the preferred way to expose anything other than the OIDC endpoints. It's not really a top priority at the moment though.

**Comment by al45tair** [comment]
@sagikazarmark gRPC doesn't really work for our specific use-case because we're trying to get this information from a Single Page App. Obviously we could write our own back-end page and have that use gRPC to fetch the list from Dex, or we could if #1489 was merged, but that seems a little heavyweight given that it's easy to add this to Dex itself, and #1489 isn't merged yet either.

I don't want to end up, in the longer term, having to fork Dex just for this, so if you're -1 on a /connectors endpoint then I suppose the Dex config-parsing approach is going to be best for now.

**Comment by sagikazarmark** [comment]
@al45tair I don't think we want to maintain two distinct APIs for similar purposes.

If the aformentioned PR lands, I would suggest calling it from your own service, exposing the connectors you want.

Let's leave this open, as the use case you mention makes sense. We might want to better support that use case in the future. Right now, it's not really a priority.

**Comment by nabokihms** [comment]
fixed in https://github.com/dexidp/dex/commit/b07e1bc9f1f7af8502bbc857f38d12feba214823
