### ISSUE TITLE
Allow to disable env variable expansion by setting DEX_EXPAND_ENV = false

### ISSUE THREAD

**Issue by heidemn-faro** [dexidp/dex#1876]
**Is your feature request related to a problem? Please describe.**
This is both a bug and a feature request.
The current way to expand env variables in the Dex config is error-prone, since it happens before the YAML parsing.
Therefore, weird hacks are needed e.g. to support `$` characters in the LDAP `bindPW`.
We're currently using a workaround there by defining an env variable `${DOLLAR}` with value `$`.
https://github.com/dexidp/dex/issues/1051
https://github.com/dexidp/dex/issues/1382

**Describe the solution you'd like to see**
Add a toplevel config variable `expandEnv` which defaults to `true` (for compatibility with existing config files), but can be set to `false` by Dex admins who don't need variable expansion at all.

**Describe alternatives you've considered**
https://github.com/dexidp/dex/issues/1838

**Additional context**
I can make this change, but @sagikazarmark or @bonifaido can you tell me if such a PR would be accepted?

**Current implementation:**

These parts would be adapted in the PR.

```go
func (s *Storage) UnmarshalJSON(b []byte) error {
	// ...
	if len(store.Config) != 0 {
		data := []byte(os.ExpandEnv(string(store.Config)))
		if err := json.Unmarshal(data, storageConfig); err != nil {
			return fmt.Errorf("parse storage config: %v", err)
		}
	}
	// ...
}

func (c *Connector) UnmarshalJSON(b []byte) error {
	// ...
	if len(conn.Config) != 0 {
		data := []byte(os.ExpandEnv(string(conn.Config)))
		if err := json.Unmarshal(data, connConfig); err != nil {
			return fmt.Errorf("parse connector config: %v", err)
		}
	}
	// ...
}

```

**Comment by sagikazarmark** [comment]
How about an env var instead that can disable this behavior? Then you don't have to parse the configuration upfront. Something like `DEX_EXPAND_ENV`.

The config layer needs a broader refactor in my opinion, but adding an env var like this would probably improve the situation in the short term.

**Comment by heidemn-faro** [comment]
@sagikazarmark an env variable is also fine for me. Then I'll implement it like this. 👍

**Comment by heidemn-faro** [comment]
Update:
`DEX_EXPAND_ENV` = falsy value -> don't expand.
Unset, or truthy value -> expand.
