### ISSUE TITLE
We should scan dependencies for CVEs

### ISSUE THREAD

**Issue by al45tair** [dexidp/dex#1900]
The Dex build process should scan dependencies for CVEs so that we're aware when we need to update things. We've started using [Nancy](https://github.com/sonatype-nexus-community/nancy) for this in some of our projects, which might be a place to start?

**Comment by sagikazarmark** [comment]
I agree, there has been quite a few vulnerabilities uncovered in several high-profile Go packages recently. I briefly looked at nancy and it seems like a great tool. If we can integrate it into GitHub actions, it'd be a great candidate, but I'd also look at GitHub's code scanning tools if they can scan dependencies.

I'm also planing to enable dependabot which should help a lot with automating upgrades.

**Comment by nabokihms** [comment]
Now we have dependabot security updates and trivy scans, so it seems like the issue is resolved.
