### ISSUE TITLE
Provide distroless images

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/dex#1924]
#### Is your feature request related to a problem?
Distroless images reduce the attack surface of an application.

#### Describe the solution you'd like to see
Provide distroless images by default. Provide alpine variants with shell for debugging purposes.

#### Additional context
Adding CA certs to distroless images might be a challenge

**Comment by ankeesler** [comment]
have y'all discussed doing this recently? i'd be interested in consuming a distroless dex in my product.

could we do this by providing a `Dockerfile.distroless` that:
1) doesn't support `gomplate` and instead has `ENTRYPOINT ["dex"]`
2) copies CA from a previous `apk add ca-certificates` step in a builder stage

alternatively, if we don't want to give up `gomplate`, could we rewrite `docker-entrypoint.sh` as a go program and inject it into the runner stage as a binary?

thanks for your consideration.

**Comment by sagikazarmark** [comment]
Hey @ankeesler 

To be honest, this isn't our top priority these days, but we'd definitely accept a PR. ;)

As for gomplate: I think it solved a ton of problems for Dex, specifically injecting secrets into various places in the config file.
I don't think we have a better solution at the moment and it would probably weird if the different images worked too differently.

The entrypoint script is quite simple though, so I think it would be trivial to rewrite it in Go.

P.S. Would you consider adding yourself to the ADOPTERS.md file?

**Comment by ankeesler** [comment]
cool, thanks for the response @sagikazarmark 

i opened an initial strawperson implementation here to get the conversation started: https://github.com/dexidp/dex/pull/2378. would love your thoughts if you have some cycles

and i will talk to my coworkers about getting us added as an adopter...
