### ISSUE TITLE
device auth flow token endpoint is not discoverable

### ISSUE THREAD

**Issue by justenwalker** [dexidp/dex#1953]
#### Is your feature request related to a problem?

#1706 implements device auth flow, which is a great feature to have. However, the token endpoint is not discoverable.

In order to exchange a `device_code` to get the authorization tokens, you have to know out-of-band to contact the `/device/token` endpoint. 

#### Describe the solution you'd like to see

It would be helpful to instead enable the `/token` endpoint as indicated by the `token_endpoint` key in the `/.well-known/openid-configuration` to handle device code authorization as well. 

In order to keep backwards compatibility, the `/device/token` endpoint can still be present, but the `/token` endpoint should detect the `grant_type = urn:ietf:params:oauth:grant-type:device_code` parameter and delegate to that same handler.

#### Describe alternatives you've considered

There isn't really an alternative beside some out-of-band way of knowing you are communicating with Dex as opposed to another OpenID connect provider.

**Comment by nabokihms** [comment]
Hello! Thank you for this issue. I personally like it!
There is a link to the corresponding RFC entry - https://tools.ietf.org/html/rfc6749#section-3.2
