### ISSUE TITLE
Docker volume support for storing sqlite3 database

### ISSUE THREAD

**Issue by mouchar** [dexidp/dex#1954]
#### Is your feature request related to a problem?
When I want to start using Dex IdP docker image, the easiest storage driver to configure is the sqlite3. But the only writable directories for user `1001` are `/tmp` and `/var/tmp`. I'd like to store sqlite3 datafile to docker volume to keep changes persistent between multiple Dex container incarnations.

Unfortunately, Docker doesn't allow to set volume ownership/permissions explicitly, but it inherits ownership from the directory, where the volume is being mounted.

#### Describe the solution you'd like to see
Create a writeable directory in Dockerfile, optionally assigning it a mount point using `VOLUME` instruction.

```dockerfile
RUN mkdir /data && chown -R 1001 /data
VOLUME /data

# existing line
USER 1001:1001
```

User can run container from image like:
```
docker run --rm -v /path/to/dex.yaml:/dex.yaml -v dex-data:/data dexidp/dex:v2.27.0 serve /dex.yaml
```
(assuming the dex.yaml points sqlite3 storage file to `/data/dex.db`)

Any changes (users, clients added via gRPC) will be kept in `dex-data` volume.

#### Describe alternatives you've considered
There are not many alternatives, except for building own image based on `dexidp/dex` image that contains this writable directory. Of course, users could also use another storage backend (like Postgres DB), but it is a more complex solution that could deter faint-hearted souls.

**Comment by nabokihms** [comment]
Hello!

With docker for mac, it is possible to simply mount a folder without changing anything in the docker file.
```bash
docker run --rm -v "$(pwd)/dex-data:/examples" -v "$(pwd)/examples/config-dev.yaml:/etc/dex/config.yaml" dexidp/dex:v2.27.0 serve  /etc/dex/config.yaml
```

However, using a Linux environment, you need extra steps.
```bash
data_dir=$(pwd)/dex-data

mkdir -p "$data_dir"
chmod 755 "$data_dir"
chown 1001 "$data_dir"
docker run --rm -v "$(pwd)/dex-data:/examples" -v "$(pwd)/examples/config-dev.yaml:/etc/dex/config.yaml" dexidp/dex:v2.27.0 serve  /etc/dex/config.yaml
```

It is an example of how you can avoid changing the docker file.

**Comment by mouchar** [comment]
Hello Maksim, thank you for your quick response. I'm working on Linux, so it is possible to use the workaround from your proposal based on bind mount. There are other issues with this solution, for example:
* you need root access to set the owner of  `$data_dir` (unless you're lucky and your local UID is 1001 :wink: )
* if you work within your $HOME directory, you end up with directories not owned by you, resulting in other troubles during backup, removal, and so on.

My idea is to use real [Docker volumes](https://docs.docker.com/storage/volumes/) to avoid such complications. Dex can be part of a more complex deployment described in docker-compose that can easily discard containers and volumes, if no longer necessary.

Therefore I'd prefer the possibility to mount docker volume into Dex container (using `-v dex-data:/examples`, and not by `-v "$(pwd)/dex-data:/examples"`)

**Comment by nabokihms** [comment]
Hello! Thanks for describing your use-case.

Real docker volumes are just folders in your example. You can use another trick with local docker volumes:
```bash
docker run --rm \
  -u :1001 \
  -v "dex-data:/examples" \
  -v "$(pwd)/examples/config-dev.yaml:/etc/dex/config.yaml" \
   dexidp/dex:v2.27.0 serve  /etc/dex/config.yaml
```

This command works on Linux-based systems (I have tested it on Ubuntu 18.04 5.3.0-51-generic with Docker 18.09.7 and non-root user).

After running the above command, we can inspect the created volume:
```
docker volume inspect dex-data
[
    {
        "CreatedAt": "2021-01-22T07:28:54Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/dex-data/_data",
        "Name": "dex-data",
        "Options": null,
        "Scope": "local"
    }
]
```
And get files permissions:
```bash
drwxr-xr-x 2 root root 4.0K Jan 22 07:33 .
drwxr-xr-x 3 root root 4.0K Jan 22 07:33 ..
-rw-r--r-- 1 root 1001  96K Jan 22 07:33 dex.db
```

I assume that you can do the same with docker-compose.

**Comment by mouchar** [comment]
Thanks, setting the UID of the dex process to root  (because `-u :1001` is effectively the same as `-u 0:1001`) really did the trick. 

However, I'm not convinced if this is the right approach, to run dex as root - it may be dangerous in some cases, despite the fact it runs in a container.

**Comment by sagikazarmark** [comment]
I wonder if using a dedicated volume makes any difference. I mean, on Linux it'll still be owned by root, won't it? So you'll still have to either manually change permissions or run Dex as root.

**Comment by mouchar** [comment]
@sagikazarmark  Nope, you don't have to manually change permissions if the directory within the container has proper ownership. Docker is smart enough to inherit the owner from the image during the volume mount process.
Example:
```dockerfile
FROM alpine:3.9
RUN mkdir /data && chown 1001 /data
USER 1001
CMD touch /data/foobar && ls -la /data
```
Build:
```
$ docker build -t demo .
```

Running **without** volume:
```
$ docker run --rm demo
total 8
drwxr-xr-x    1 1001     root          4096 Jan 22 11:20 .
drwxr-xr-x    1 root     root          4096 Jan 22 11:20 ..
-rw-r--r--    1 1001     root             0 Jan 22 11:20 foobar
```
Running **with** volume:
```
docker run -v demo-vol:/data --rm demo
total 8
drwxr-xr-x    2 1001     root          4096 Jan 22 11:21 .
drwxr-xr-x    1 root     root          4096 Jan 22 11:21 ..
-rw-r--r--    1 1001     root             0 Jan 22 11:21 foobar
```

Final volume contents:
```
$ sudo LC_ALL=C ls -la /var/lib/docker/volumes/demo-vol/_data
total 8
drwxr-xr-x 2 1001 root 4096 Jan 22 12:21 .
drwxr-xr-x 3 root root 4096 Jan 22 12:21 ..
-rw-r--r-- 1 1001 root    0 Jan 22 12:21 foobar
```
Note the owner of the directory itself (the root of the volume) is owned by `1001` without any manual intervention. That was made automatically by Docker daemon. And the `touch` process ran with uid=1001 privileges, not root.

**Comment by sagikazarmark** [comment]
@mouchar Cool. Haven't used linux in a while (my greatest regret of life so far), so I wasn't sure how that would work.

How about adding a `/var/dex` directory with the proper owner?
I can see that the group is not set in your examples. Is there a reason for that?

I think we can probably omit the `VOLUME` entry from the Dockerfile: Dex shouldn't write anything there by default that would need preserving between container restarts, you'll always do that manually when needed.

**Comment by mouchar** [comment]
First, I thought of `/examples` to make the command `docker run -v "$(pwd)/examples/config-dev.yaml:/config.yaml" dexidp/dex serve config.yaml` instantly working, but `/var/dex` looks much better as it fits Linux Filesystem Hiererchy Standard.

The `/var/dex` directory purpose should be documented somewhere close to the image.

I didn't mention group since it is not important in this case (group write-bit is not set on the directory). But you should set the ownership to 1001 for both user and group: `chown 1001:1001 /var/dex`.

I agree the `VOLUME` is absolutely unnecessary.

**Comment by sagikazarmark** [comment]
I wonder if we should do the same for configuration and use /etc/dex

Maybe we should also add a default config to the image as well

**Comment by sagikazarmark** [comment]
See the linked PR ☝️
