### ISSUE TITLE
go-ldap panic on arm devices

### ISSUE THREAD

**Issue by salmanisd** [dexidp/dex#2011]
**Describe the bug**
dex uses go-ldap v2 which has problems running on my arm device giving error like
`LDAP Result Code 200 "Network Error": ldap: response channel closed`

**To Reproduce**
run current version of dex on an arm device and try to do an ldap auth request through Login page

#### Environment

- Dex version: 2.27.0
- Storage type: sqlite3
- Installation type (official docker image, helm chart, etc.): yocto compiled binary

#### Anything else we should know?
This is common issue caused by go-ldap v2 and can be fixed by updating ldap to use go-ldap v3.

for reference similar issues are following
https://github.com/hashicorp/vault/issues/6135
https://github.com/portainer/portainer/issues/3244
https://github.com/go-ldap/ldap/issues/195

**Comment by sagikazarmark** [comment]
Thanks @salmanisd for opening this issue (and the solution/links).

We'll try to prioritize the issue, but feel free to submit PRs.
