### ISSUE TITLE
Is there anyway to configure multiple ldap hosts for high availibility

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [dexidp/dex#2062]
Is there anyway to configure multiple ldap hosts for high availibility using dex ldap connector

connectors:
  - type: ldap
    id: ldap
    name: LDAP
    config:
      host: ''
      insecureSkipVerify: true
      bindDN: ''
      bindPW: 
      usernamePrompt:

**Comment by nabokihms** [comment]
Right now, there is no such feature in dex.

The possibility of implementing this was discussed in the issue 
https://github.com/dexidp/dex/issues/1548

Corresponding PR https://github.com/dexidp/dex/pull/1904

**Comment by nabokihms** [comment]
Closing this issue. If you have questions about the subject, write them to #1904.
