### ISSUE TITLE
LDAP error after upgrading argocd version to v2.0.0.

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [dexidp/dex#2078]
Hi, We’re facing issue w.r.t dex unable to login via LDAP after upgrading argocd version to v2.0.0. Getting the following error message when try to login via LDAP.
502 Bad Gateway
 unknown app state zZZcSUIYue
When we verify the dex pod logs authentication was successful.
Same configuration is working fine in version (v1.8.7).
Is it bug? or do we need make any changes to make it work. Please suggest

**Comment by sagikazarmark** [comment]
At first sight it doesn't seem to be a Dex issue to me. At least ` 502 Bad Gateway` and ` unknown app state zZZcSUIYue` are certainly not related to LDAP and are probably not emitted by Dex either.

How did you come to the conclusion that it was a Dex related issue? If ArgoCD login doesn't work after upgrading, it can still be a lot of other things, especially if Dex logs suggest that the login was successful.

**Comment by s-u-b-h-a-k-a-r** [comment]
The issue was not happening with other than v2.0.0 versions.

**Comment by sagikazarmark** [comment]
As far as I can tell v2 is a rather large release, so there could be several things going wrong. From the information you've provided it's not obvious to me that Dex is the culprit, nor can I properly debug this issue. I'd suggest to ask help from the ArgoCD community first.

**Comment by s-u-b-h-a-k-a-r** [comment]
Sure thank you.. I added a issue with ArgoCD community also.

**Comment by sagikazarmark** [comment]
Would you mind linking the two issues together?

**Comment by s-u-b-h-a-k-a-r** [comment]
https://github.com/argoproj/argo-cd/issues/6012

**Comment by sagikazarmark** [comment]
Closing as it doesn't seem to be a Dex issue. Feel free to open a new issue with more details if there is evidence that it's a Dex issue.
