### ISSUE TITLE
Atlassian-Crowd-Connector

### ISSUE THREAD

**Issue by icebear74** [dexidp/dex#2159]
#### Expected behavior (what you expected to happen)
Dex should Start :)

#### Actual behavior (what actually happened)
Dex won't start
#### Steps to reproduce

Create Copy of Example Yaml File
Append Config for Atlassian Crowd:

- type: atlassian-crowd
  config:
    baseURL: "http://crowd.xxx.com/crowd"
    clientID: "dex"
    clientSecret: "xxx"
    usernamePrompt: "Login"
    preferedUsernameField: "name"

#### Environment

./dex version
Dex Version: f45a89f6b3e9dd52c382e47575cf82ae67d54942-dirty
Go Version: go1.16.3
Go OS/ARCH: linux amd64

#### Anything else we should know?
Errormessage: ./dex serve ../examples/config-oda.yaml
error parse config file ../examples/config-oda.yaml: error unmarshaling JSON: no password hash provided

Also tryed PW Hash from String Password and self genereated Hash and Plain Text ..

**Comment by sagikazarmark** [comment]
Please provide the whole configuration file, properly formatted in a code block. This error usually comes from the password connector, so it's probably not related to the atlassian connector.

**Comment by icebear74** [comment]
Hi,
here the Complete config in a Code Block.

`issuer: http://haproxy-01.oda-devops.local:5556/dex

storage:
  type: sqlite3
  config:
    file: ../examples/dex.db

web:
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558

staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

connectors:
- type: mockCallback
  id: mock
  name: Example

enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

- type: atlassian-crowd
  config:
    baseURL: "http://crowd.opdatata.com/crowd"
    clientID: "dex"
    clientSecret: "dex"
    usernamePrompt: "Login"
    preferedUsernameField: "name"



`

**Comment by sagikazarmark** [comment]
This isn't correct. The following should be under `connectors`:

```
- type: atlassian-crowd
  config:
    baseURL: "http://crowd.opdatata.com/crowd"
    clientID: "dex"
    clientSecret: "dex"
    usernamePrompt: "Login"
    preferedUsernameField: "name"
```

**Comment by icebear74** [comment]
Tnx. That was it .. My Mistake . Sorry .
