### ISSUE TITLE
Internal Server Error: Login error -- Connector \"github\" returned error when creating callback: expected callback URL \"https://<dex Endpoint>/callback\" did not match the URL in the config \"https://<dex Endpoint>/oauth2/callback\

### ISSUE THREAD

**Issue by Sandy1438** [dexidp/dex#2166]
Hello There,

I'm trying to secure K8s dashboard by using Oauth2_Proxy infront of it and using Dex as Identity provider Github as external auth provider.

#### Expected behavior (what you expected to happen):
--------------------------------------------------------------
When I login to K8s dashboard url which is exposed by nginx ingress it will redirect to Oauth2_Proxy > Dex > Github > K8s dashboard.

Authorization callback URL in Github is set as  as per Oauth2_Proxy provider doc as https://dex endpoint/oauth2/callback

Dex config file content:
---------------------------

    issuer: https://<dex endpoint>/
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    oauth2:
      skipApprovalScreen: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID_UI
        clientSecret: $GITHUB_CLIENT_SECRET_UI
        redirectURI: https://<dex endpoint>/oauth2/callback
        orgs:
        - name: 4k8s
          teams:
          - devops
    staticClients:
    - id: <client id>
      redirectURIs:
      - 'http://<oauth2_proxy endpoint>/oauth2/callback'
      name: 'oidcui'
      secret: <client secret>

#### Actual behavior (what actually happened):
-----------------------------------------------------
When I access the K8's dashboard url it redirects to Dex with error as below:

Internal Server Error: Login error

What I see in dex pod logs is as below:

time="2021-06-09T09:08:21Z" level=error msg="Connector \"github\" returned error when creating callback: expected callback URL \"https://<dex endpoint>/callback\" did not match the URL in the config \"https://<dex endpoint>/oauth2/callback\""

#### Steps to reproduce

1. ...
2. ...
3. ...

#### Environment

- Dex version: Latest tag
- Storage type: Kubernetes inCluster
- Installation type (official docker image, helm chart, etc.): quay.io/dexidp/dex:latest deployed in self managed kubernetes

Any help would be much appreciated?

BR,
Sandy.

**Comment by sagikazarmark** [comment]
I think the error message is quite self-describing: you should use `https://<dex endpoint>/callback` as a redirect URI.

A side note: `quay.io/dexidp/dex:latest` is probably not the best image or tag to use. The primary source for images is [GitHub](https://github.com/orgs/dexidp/packages/container/package/dex) now. Also, I wouldn't recommend using the latest tag either as it points to the latest master, not the latest tagged release.

**Comment by Sandy1438** [comment]
Thanks a lot @sagikazarmark ! 
I have corrected it and now I can redirect to Github and presented with the sign in page.
Once I have provided with my credentials on Github sign in page I get error as : 404 page not found

I don't see any error in dex pod logs or any logs being written to dex pod related authentication success ack. Not sure much about hence, do bear with my silly queries .

I had checked the ingress controller logs and see this as below:

192.168.86.128 - - [09/Jun/2021:10:25:32 +0000] "GET /auth?approval_prompt=force&client_id=oidcsso&redirect_uri=http%3A%2F%2Foauth2proxy.oidcdex.ga%2Foauth2%2Fcallback&response_type=code&scope=openid+email+profile+groups&state=88nFXBFWOf5P3flE06ikWrkU5PsqxGIrzz0xOcTFfuo%3Ahttps%3A%2F%2Fk8ui.oidcdex.ga%2F HTTP/2.0" 302 65 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41" 600 0.012 [dex-dex-5556] [] 192.168.86.182:5556 65 0.012 302 172a9caae14b732fb50bc63ac9f41e39
192.168.86.128 - - [09/Jun/2021:10:25:32 +0000] "GET /auth/github?req=m2bdkyfk3eecfs5u47saazufl HTTP/2.0" 302 244 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41" 47 0.012 [dex-dex-5556] [] 192.168.86.182:5556 244 0.013 302 ab8d9278ec82c717bd8fc1dec9ce9a53
192.168.86.128 - - [09/Jun/2021:10:25:43 +0000] "GET /oauth2/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=m2bdkyfk3eecfs5u47saazufl HTTP/2.0" 404 19 "https://github.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41" 270 0.001 [dex-dex-5556] [] 192.168.86.182:5556 19 0.000 404 8f9b9f8a1c6682983f8377482f0c0a65

Is that something I need to check with dex config once again or at oauth2_proxy part?

**Comment by sagikazarmark** [comment]
I can't really tell you what causes the 404. What do you see in your browser's address bar?

The error in the logs are related to the incorrect callback URL, so I think that's the previous error.

**Comment by Sandy1438** [comment]
I see as below screen shot.  

_>>_The error in the logs are related to the incorrect callback URL, so I think that's the previous error.__  Yes I too feel the same that but not sure where to correct it .

![image](https://user-images.githubusercontent.com/71320072/121357368-64763580-c94f-11eb-8147-e035a04e20a9.png)

https://dex.oidcdex.ga/oauth2/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=ioe5pf7xgtyophkn5gfy7cf75

**Comment by sagikazarmark** [comment]
Somewhere you still have `/oauth2/callback`. Probably github? I don't know about oauth2_proxy, but everything related to Dex should go to `/callback`.

Sorry, this isn't a bug (something is misconfigured on your end), so I'm closing this issue. Please open a discussion instead.
