### ISSUE TITLE
Unable to build dex  make: *** [Makefile:34: generate] Error 1

### ISSUE THREAD

**Issue by pnatraj** [dexidp/dex#2183]
pulled the git repo and while trying to build the repo i am getting the below error 

@
PHONY: generate
     generate:
         @go generate $(REPO_PATH)/storage/ent/

Error 

go: downloading github.com/mattn/go-sqlite3 v1.14.7
go: downloading entgo.io/ent v0.8.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: extracting github.com/pkg/errors v0.9.1
go: extracting gopkg.in/square/go-jose.v2 v2.6.0
go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
go: extracting github.com/mattn/go-sqlite3 v1.14.7
go: extracting entgo.io/ent v0.8.0
go: downloading github.com/google/uuid v1.2.0
go: extracting github.com/google/uuid v1.2.0
go: extracting golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
-mod=mod not supported (can be '', 'readonly', or 'vendor')
storage/ent/generate.go:3: running "go": exit status 1
make: *** [Makefile:34: generate] Error 1

Environment : Ubuntu 20.4

**Comment by sagikazarmark** [comment]
You are probably on an old Go version. Upgrade to the latest version and it should work.

**Comment by pnatraj** [comment]
go version go1.13.8 linux/amd64

**Comment by sagikazarmark** [comment]
Yeah, that's quite old. Dex requires 1.16

**Comment by pnatraj** [comment]
sorry got it working with 1.16
