### ISSUE TITLE
Parse non-standard groups claim as string csv

### ISSUE THREAD

**Issue by blut** [dexidp/dex#2185]
Hello

Our upstream ID provider offers groups as claim in the ID Token formatted as groups: "|group1|group2|".
Since [groups are parsed as []interface{}](https://github.com/dexidp/dex/blob/master/connector/oidc/oidc.go#L325-L343), the claim is never found and the string is neither parsed, nor passed to any client.

I'd like to suggest optionally parsing the groups claim as csv with configurable separator e.g. along the lines of
```
            vs := claims[groupsKey]
            groupsStr, ok := vs.(string)
            if ok {
                for _, v := range strings.Split(groupsStr, c.groupsSep) {
                    if v == "" {
                        continue
                    }
                    groups = append(groups, v)
                }
            }
```
Ideally, the solution would allow custom parsing for any separate claimMapping.

Is there a preferred way or suggestion how to achieve the desired result?

**Comment by sagikazarmark** [comment]
We plan to implement a middleware layer that would allow these kinds of transformations: #1635

What I recommend in the meantime is building a custom version of Dex with a modified connector.

**Comment by blut** [comment]
Thanks for the info. That's what I'm currently running.

**Comment by sagikazarmark** [comment]
Closing as we already track this issue.
