### ISSUE TITLE
CSS is delivered with wrong content type in 2.29.0

### ISSUE THREAD

**Issue by felixfontein** [dexidp/dex#2202]
#### Expected behavior (what you expected to happen)
The styles.css file is delivered with Content-Type `text/css`. This works with 2.28.1 and earlier.

#### Actual behavior (what actually happened)
Since the latest release (2.29.0), the styles.css file is delivered with Content-Type `text/plain`.

If also the security header `X-Content-Type-Options: nosniff` is sent, browsers will refuse to load the CSS file, and the login form looks pretty ugly.

**Comment by nabokihms** [comment]
I cannot reproduce it locally. Could you tell us more about your environment? 
We have a template for bug reports.

**Comment by sagikazarmark** [comment]
Well, I can't reproduce it either:

```
❯ curl -I http://127.0.0.1:5556/dex/theme/styles.css
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 1791
Content-Type: text/css; charset=utf-8
Date: Thu, 01 Jul 2021 07:33:49 GMT
```

Works from the browser, too.

Do you have anything in the middle that might cause a change in the Content-Type header @felixfontein?

**Comment by felixfontein** [comment]
Sorry, I was trying to get too much done before a longer series of meetings :)

The content type was a wrong indication, the content type was `text/plain` because the URL 404ed. I'm using the official dex container with a custom theme. I think this is related to #2054: I had to change the `theme/` directory mount from `/web/themes/mytheme` to `/srv/dex/web/themes/mytheme`, and add `dir: /srv/dex/web` to the `frontend` section in the config file (so far I had no `dir` entry in the `frontend` config). With these changes, it worked again.

**Comment by sagikazarmark** [comment]
Yeah, that part changed a bit. You can find the updated documentation here: https://dexidp.io/docs/templates/

I take it as the issue is resolved then.

**Comment by felixfontein** [comment]
It is resolved for me, thanks. It mainly wasn't clear from the changelog that this is a breaking change for (some?) users with own themes.
