### ISSUE TITLE
GitLab Connector - options for add custom CA certificate or skip certverification.

### ISSUE THREAD

**Issue by PigNatovsky** [dexidp/dex#2205]
#### Is your feature request related to a problem?

I'm trying to use Dex with ArgoCD on our on-prem cluster (about 100 nodes with 16 cores and 64GB RAM per machine). And we want to integrate Dex with our on-prem GitLab. But we can;t - our organization has internal CA, so DEX  can't communicate with our GitLab.

#### Describe the solution you'd like to see

It will be nice, if GitLab connection will have options like CAPath or skipCertificateValidation.

#### Describe alternatives you've considered

As alternative I can find places where oauth2 client is searching for CA certificates (GitLab connector uses golang.org/x/oauth2).

**Comment by nabokihms** [comment]
Looks like a duplicate of https://github.com/dexidp/dex/issues/1542

**Comment by PigNatovsky** [comment]
True, it's the same problem. I'm closing issue.
