### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by ReggieCarey** [dexidp/dex#2207]
The documentation does not include installation instructions.

You have instructions to install the git repo, and instructions to build the dex binary,
but that is NOT installation instructions.

Where is the latest version?

**Comment by sagikazarmark** [comment]
The documentation is a bit lacking at the moment, but we are working on that. It does contain a bunch of configuration examples, so if you have the binary or the container image, you can run it.

There is a helm chart that you can use to install it on Kubernetes: https://github.com/dexidp/helm-charts/tree/master/charts/dex
