### ISSUE TITLE
'Error response from daemon: manifest unknown' when trying to pull ghcr.io/dexidp/dex:v2.30.1

### ISSUE THREAD

**Issue by ffdybuster** [dexidp/dex#2328]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.30.1

### Storage Type

SQLite

### Installation Type

Official container image

### Expected Behavior

I run `docker pull ghcr.io/dexidp/dex:v2.30.1` to pull the image, and it fails with `Error response from daemon: manifest unknown`. Either there's some incompatibility between the image and Docker, or there's a problem with the image.

### Actual Behavior

```.sh
$ docker pull ghcr.io/dexidp/dex:v2.30.1
Error response from daemon: manifest unknown
```

### Steps To Reproduce

Run `docker pull ghcr.io/dexidp/dex:v2.30.1`

### Additional Information

```.sh
$ docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:26 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by sagikazarmark** [comment]
The CI job is failing for some reason. We are working on a fix.

**Comment by sagikazarmark** [comment]
Should be fixed.

**Comment by ffdybuster** [comment]
I can confirm that 2.30.2 works fine! Thanks a lot!
