### ISSUE TITLE
Come up with a formal process for large proposals

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/dex#2370]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

There are at least two big changes in the queue for Dex:

- External connectors
- Middleware

Without trying to diminish the value people already invested in investigating/implementing, I believe we lack the clarity on a lot of details that would help us make decisions, come up with a plan and speed up the execution.

### Proposed Solution

I'd like us to take a step back and write some sort of proposals that cover questions like:

- scope
- impact of change to existing features
- goals
- non-goals
- architectural view
- implementation details

The point is not putting more burden on the maintainers, but to come up with a set of questions/guidelines that help them figure out good solutions for these complex issues.

**Comment by sagikazarmark** [comment]
@nabokihms this is basically done by having DEPs, right?

**Comment by nabokihms** [comment]
Yes, I think we can close this for now.
