### ISSUE TITLE
Bitbucket's `/teams` endpoint is now depreacted.

### ISSUE THREAD

**Issue by rahulchheda** [dexidp/dex#2391]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.30.x

### Storage Type

Postgres

### Installation Type

Official container image

### Expected Behavior

Bitbucket OAuth should work

### Actual Behavior

Gives error:
```
{"level":"error","msg":"Failed to authenticate: bitbucket: get user teams: 404 Not Found: {\"type\": \"error\", \"error\": {\"message\": \"This endpoint has been removed. See our documentation for more information. https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-user-permissions-teams-get\"}}","time":"2022-01-27T07:21:52Z"}
```

### Steps To Reproduce

Try Bitbucket's OAuth

**Comment by JanisOrlovs** [comment]
Hello,

What is the timeline for this issue to be merged? This is becoming an issue for us.

**Comment by slinstaedt** [comment]
Hi, is there any chance to release this change soon? The bitbucket connector is not working anymore since xmas last year. Bitbuckets teams endpoint is not deprecated (that actually happend several months before), but simply removed.

**Comment by nabokihms** [comment]
@slinstaedt v2.30.2 with this fix is coming.

**Comment by slinstaedt** [comment]
Thanks, I am really appreciating your work :)

**Comment by Pixelsmith** [comment]
I'm still receiving this error on v4.1.6, even after updating.

Has the patch been released yet?

**Comment by slinstaedt** [comment]
v2.30.3 was released at least on [docker hub](https://hub.docker.com/layers/dexidp/dex/v2.30.3/images/sha256-c403d22c7f1562656edc17b4573dbb04906ef9b52c2048e7f2245a158389b946?context=explore).
