### ISSUE TITLE
Latest docker images fail to start

### ISSUE THREAD

**Issue by petrm** [dexidp/dex#2485]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

docker tag latest

### Storage Type

SQLite

### Installation Type

Official container image

### Expected Behavior

Expecting dex to start successfully.

### Actual Behavior

Docker images tagged latest fail with following error:
dex                   | exec /usr/local/bin/docker-entrypoint: exec format error

Rolling back to tag v2.31.1 fixes the issue.

**Comment by sagikazarmark** [comment]
Thanks for reporting! We recently changed how images are built and that seems to break the multi-platform builds. We will fix it shortly.

**Comment by sagikazarmark** [comment]
This should be fixed
