### ISSUE TITLE
Dex OIDC connector requires id_token in response body from IDPs, when using a grant_type of refresh_token

### ISSUE THREAD

**Issue by Blorpy** [dexidp/dex#2498]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.31.0

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

I would expect that dex be compatible with IDPs that do not issue an id_token again when using a grant_type of refresh_token, or that the reasons why this can't be supported are documented. 

### Actual Behavior

Dex fails to use the IDP refresh token to get a new access token. 

### Additional Information

As per https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse an id_token may not be contained in a reply on the token endpoint, when using a grant type of refresh_token. 

id_token seems to be required in the current code https://github.com/dexidp/dex/blob/master/connector/oidc/oidc.go#L278

```
Upon successful validation of the Refresh Token, the response body is the Token Response of [Section 3.1.3.3](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse) except that it might not contain an id_token.
```

The body of the response from my IDP looks like this:

```
{
    "access_token": "redacted_access",
    "expires_in": 3599,
    "refresh_token": "redacted_refresh",
    "token_type": "Bearer"
}
```

### Logs

```shell
time="2022-04-28T21:37:31Z" level=error msg="failed to refresh identity: oidc: no id_token in token response"
```

**Comment by Blorpy** [comment]
It looks like this may be linked to a limitation upstream in kubernetes. https://github.com/kubernetes/kubernetes/issues/36847 reading through this issue indicates that IDPs that do not return an id_token when using a refresh_token grant are not fully supported. 

I'm going to leave this open for further comment from maintainers or other community members. It's not clear to me whether there is a viable workaround here, but if I have time I will try and look at how keycloak's implementation behaves in the case of an upstream IDP not returning an id_token on refresh (does it choke, or does it hit the userinfo endpoint or something to try and fill in the gaps).

**Comment by nabokihms** [comment]
Thank you for pointing this out.

From my point of view, Dex should support such providers and act as a shim between providers without id_tokens in refresh responses and Kubernetes (I still believe that running Dex inside Kubernetes clusters is the most common use case).

As mentioned above, the solution should be making id_token optional and relying only on claims from the user info endpoint response (if we can extract claims from the user info endpoint, it should be ok).

@Blorpy, do you want to go ahead and make the necessary changes?

**Comment by Blorpy** [comment]
I took a swing at this in #2505, will wait for maintainer review @nabokihms
