### ISSUE TITLE
ldap connector for AD does not return the groups user belongs to

### ISSUE THREAD

**Issue by gary-RR** [dexidp/dex#2603]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

100246328bffe24ca276812daa0fe06d1fc25a8d-dirty

### Storage Type

SQLite

### Installation Type

Binary

### Expected Behavior

I was expecting that the AD groups a user belongs to would be returned as claims, but they don't. I've followed the sample code here: https://dexidp.io/docs/connectors/ldap/#example-searching-a-active-directory-server-with-groups

It authenticates against AD fine and returns the basic info such as user ID, etc, but no groups. 

### Actual Behavior

The LDAP connector when connected to AD, does not return the groups a user belongs to. Again I use the code provided here:  code here: https://dexidp.io/docs/connectors/ldap/#example-searching-a-active-directory-server-with-groups

Thank you!

### Steps To Reproduce

1- Used the sample app here: https://dexidp.io/docs/getting-started/
2- Modified the "connectors:" section in the "config-dev.yaml" file, commented out the " type: mockCallback" and added the "- type: ldap" section from: https://dexidp.io/docs/connectors/ldap/#example-searching-a-active-directory-server-with-groups 
3- Changed the AD-specific info to my AD info.
4- Started the app when I looked at the claims returned, I didn't see any AD groups for the user (the user belongs to several groups). Here is what it returns:
          baseDN: CN=Users,DC=acme,DC=pri
          filter: (objectClass=user)
          username: sAMAccountName #name
          idAttr: sAMAccountName #uid
          emailAttr: sAMAccountName #userPrincipalName #mail
          nameAttr: displayName #mail

And the app run time debugs info show,, as you can see groups are empty:

time="2022-07-24T12:49:17Z" level=info msg="login successful: connector \"ad\", username=\"alice\", preferred_username=\"\", email=\"alice\", groups=[]" 

### Logs

```shell
time="2022-07-24T12:49:17Z" level=info msg="login successful: connector \"ad\", username=\"alice\", preferred_username=\"\", email=\"alice\", groups=[]"
```

**Comment by gary-RR** [comment]
I should point out that this is the ldap query that should be constructed by the connector to properly extract groups:

"(&(objectClass=group)(member=cn=alice,CN=Users,DC=xxx,DC=yyyi))"

It seems that the connector does not format the query properly. Thanks,

**Comment by gary-RR** [comment]
I also ran tshark on the Linux client to view traffic and messages sent to and received from AD as shown below. It looks like only the first query (getting basic attributes) is sent to AD but not the group membership one:

#*********************************Request**********************************
Lightweight Directory Access Protocol
    LDAPMessage searchRequest(2) "CN=Users,DC=xxx,DC=yyy" wholeSubtree
        messageID: 2
        protocolOp: searchRequest (3)
            searchRequest
                baseObject: CN=Users,DC=xxx,DC=yyy
                scope: wholeSubtree (2)
                derefAliases: neverDerefAliases (0)
                sizeLimit: 0
                timeLimit: 0
                typesOnly: False
                Filter: (&(objectClass=user)(sAMAccountName=alice))
                    filter: and (0)
                        and: (&(objectClass=user)(sAMAccountName=alice))
                            and: 2 items
                                Filter: (objectClass=user)
                                    and item: equalityMatch (3)
                                        equalityMatch
                                            attributeDesc: objectClass
                                            assertionValue: user
                                Filter: (sAMAccountName=alice)
                                    and item: equalityMatch (3)
                                        equalityMatch
                                            attributeDesc: sAMAccountName
                                            assertionValue: alice
                attributes: 4 items
                    AttributeDescription: sAMAccountName
                    AttributeDescription: sAMAccountName
                    AttributeDescription: distinguishedName
                    AttributeDescription: displayName


#*********************************Response**********************************
Lightweight Directory Access Protocol
    LDAPMessage searchResEntry(2) "CN=alice,CN=Users,DC=xxx,DC=yyy" [1 result]
        messageID: 2
        protocolOp: searchResEntry (4)
            searchResEntry
                objectName: CN=alice,CN=Users,DC=xxx,DC=yyy
                attributes: 3 items
                    PartialAttributeList item distinguishedName
                        type: distinguishedName
                        vals: 1 item
                            AttributeValue: CN=alice,CN=Users,DC=xxx,DC=yyy
                    PartialAttributeList item displayName
                        type: displayName
                        vals: 1 item
                            AttributeValue: alice
                    PartialAttributeList item sAMAccountName
                        type: sAMAccountName
                        vals: 1 item
                            AttributeValue: alice

**Comment by gary-RR** [comment]
Found the issue. I had to pass "groups" in the gangway's scope.

**Comment by subasathees** [comment]
@gary-RR, thats great !!, can you pls share your full config of gangway where you put.
