### ISSUE TITLE
integration testing: OpendID Connect compliance tests

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#262]
This has been brought up as a precondition of #42 and #107 but I'm opening a new issue because it's worth addressing on its own.

Use outside compliance tests to evaluate dex's OpenID Connect implementation.

Relevant links:
- [rohe/oidctest](https://github.com/rohe/oictest)
- [OpenID certification page](https://openid.net/certification/)
- [_OpenID Connect Conformance Profiles v1.0_](https://openid.net/wordpress-content/uploads/2015/03/OpenID-Connect-Conformance-Profiles.pdf)

**Comment by rsoletob** [comment]
As we talked in [dex-dev](https://groups.google.com/forum/#!topic/dex-dev/rCc6ieFb6P0), here is the full report: 

[oidc-compliance-test-result.zip](https://github.com/coreos/dex/files/171828/oidc-compliance-test-result.zip)

**Comment by ericchiang** [comment]
Wow there's a lot of stuff in there. I'll take a look through them in a bit and try to come up with an issue list.

Would you like to open a PR adding the compliance test scripts to this repo? Eventually (once we fix a sufficient number of them) I'd like to add them to the travis tests.

**Comment by rsoletob** [comment]
I'm going to research about this. Some tests need user interaction and I don't know if it could work without an user.

**Comment by karimhm** [comment]
+1

**Comment by sagikazarmark** [comment]
Progress will be tracked here: https://github.com/orgs/dexidp/projects/3/views/1
