### ISSUE TITLE
JWT Token too long and is Truncated in Input Control

### ISSUE THREAD

**Issue by CenturySparkle** [dexidp/dex#2642]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

Unknown

### Storage Type

Kubernetes

### Installation Type

Other (specify below)

### Expected Behavior

I am a user.  I have not installed it, someone else did.

The problem is that the JWT tokens for our company are too long for the input control and they are truncated and many people cannot login because of a bad token.  Please increase the length of the token input control.

### Actual Behavior

Server responds with 401 because token is truncated

### Steps To Reproduce

Create a large token with many AD groups, once the token passes a certain length login fails

**Comment by nabokihms** [comment]
Hello, @CenturySparkle. It does not seem like a Dex problem. Internally, Dex does not truncate tokens. We need to know more about authentication flow in your cluster to help, e.g., how traffic comes to the cluster and whether there are any proxies.

Suggestions that may help:
1. Check that passing big-sized bodies are allowed (headers are body parts).
2. It is possible to filter groups on input by using the `filter` option. Not necessarily all groups are required for authorization in the cluster. Some groups may serve other purposes.

**Comment by nabokihms** [comment]
Closing this because of the staleness. Feel free to reopen this issue if you still have a problem.
