### ISSUE TITLE
Google Connector with groups gives invalid_scope

### ISSUE THREAD

**Issue by andrejvanderzee** [dexidp/dex#2653]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

v2.33.0

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

When specifying `scopes: ["email", "profile", "groups"]`  I expect groups in the log output. 

### Actual Behavior

Unfortunately I get the following error in my browser:

```
Sign in with Google

Authorization Error
Error 400: invalid_scope
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile], invalid=[groups]}

[Learn more]
```

### Additional Information

The problem is that we have to add `groups` to scope otherwise `s.Groups` will be false and groups are never fetched:
https://github.com/dexidp/dex/blob/v2.33.0/connector/google/google.go#L221

When I patch google.go and set `s.Groups = true` we get the groups, as expected.

### Logs

```shell
Without the patch:

{
  "level": "info",
  "msg": "login successful: connector \"google\", username=\"Test User\", preferred_username=\"\", email=\"test@***.io\", groups=[]",
  "time": "2022-09-07T06:59:07Z"
}
```

With the patch:
```{
  "level": "info",
  "msg": "login successful: connector \"google\", username=\"Test User\", preferred_username=\"\", email=\"test@***.io\", groups=[\"test-group@***.io\"]",
  "time": "2022-09-07T06:59:07Z"
}
```
```

**Comment by andrejvanderzee** [comment]
Well problem seems that Google signin does not accept scope `groups` anymore. This (in my opinion acceptable) patch makes it work for us (so if one specifies `serviceAccountFilePath` and `adminEmail`, then groups are fetched):

```
$ git diff connector/google/google.go
diff --git a/connector/google/google.go b/connector/google/google.go
index 1b515b8e..b6583ec8 100644
--- a/connector/google/google.go
+++ b/connector/google/google.go
@@ -218,7 +218,7 @@ func (c *googleConnector) createIdentity(ctx context.Context, identity connector
        }
 
        var groups []string
-       if s.Groups && c.adminSrv != nil {
+       if c.adminSrv != nil {
                groups, err = c.getGroups(claims.Email, c.fetchTransitiveGroupMembership)
                if err != nil {
                        return identity, fmt.Errorf("google: could not retrieve groups: %v", err)
```

Would this patch be accepted if I open an official MR?

**Comment by damieva** [comment]
Hi community!
I had the same problem but you can configure dex to avoid invalid_scope error and aldo fetch the groups.
Assumtions: `serviceAccountFilePath` and `adminEmail` are properly configured as per Dex documentation.
Solution: you need to add the following scopes: `openid,profile,email,groups` and the following custom claim:
`      claimMapping:
        - groups: https://www.googleapis.com/auth/admin.directory.group.readonly
`

Google API does not have any alias for `groups` like the other scopes (`openid,profile,email`) so we need to map it specifically. In my case I'm using the harbor client and I'm connecting to Google OIDC though Dex, so I must indicate some scopes (`openid,profile,email,groups`) and I can't put there an URL like the example but I suppose that the following block could also run:
`scopes:
  - openid
  - profile
  - email
  - https://www.googleapis.com/auth/admin.directory.group.readonly
`

**Comment by andrejvanderzee** [comment]
Thanks @damieva !

This works indeed. Closing issue.
