### ISSUE TITLE
Building the dex binary returning error with golang version 1.15

### ISSUE THREAD

**Issue by Dmaddu** [dexidp/dex#2749]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

latest

### Storage Type

Postgres

### Installation Type

Binary

### Expected Behavior

The compilation should work without any errors. 

### Actual Behavior

getting below error while executing `make build`
package embed is not in GOROOT (/usr/local/go/src/embed)
package io/fs is not in GOROOT (/usr/local/go/src/io/fs)

### Steps To Reproduce

<img width="1222" alt="Screenshot 2022-11-24 at 12 08 38 PM" src="https://user-images.githubusercontent.com/44021874/203712132-a6245198-eb03-46fd-8c31-07ffe0a31b38.png">

**Comment by Dmaddu** [comment]
<img width="880" alt="Screenshot 2022-11-24 at 11 56 29 AM" src="https://user-images.githubusercontent.com/44021874/203712286-882819f6-2e11-4fd6-a701-7bee51c22886.png">

**Comment by nabokihms** [comment]
Good catch, thank you. We will fix the doc.
