### ISSUE TITLE
Device Authorization Flow broken with etcd storage

### ISSUE THREAD

**Issue by MM53** [dexidp/dex#3118]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.37.0

### Storage Type

etcd

### Installation Type

Official container image

### Expected Behavior

Being able to use the oidc Device Authorization Flow with any type of storage. 

### Actual Behavior

When using the Device Authorization Flow with etcd as storage all login attempts resulted in an error page complaining about missing data like clientId, clientSecret, ... although those information were provided while generating the login url.

**Comment by nabokihms** [comment]
Fixed by https://github.com/dexidp/dex/pull/3119
