### ISSUE TITLE
ID Token - refresh tokens related config - specifically - lost

### ISSUE THREAD

**Issue by pankajmt** [dexidp/dex#3275]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

NA

### Storage Type

etcd

### Installation Type

Official Helm chart

### Expected Behavior

Remember being able to get to https://dexidp.io/docs/id-tokens/ on Dec 22nd. Still in the cache for search engine robots. Trying to find the page in the docs hierarchy, but thought of calling it out. 

### Actual Behavior

Be able to read contents of https://dexidp.io/docs/id-tokens/. More specifically refresh tokens related config. 

### Steps To Reproduce

NA

### Additional Information

NA

### Configuration

```yaml
NA
```

### Logs

```shell
NA
```

**Comment by pankajmt** [comment]
found it, https://dexidp.io/docs/tokens/

**Comment by nabokihms** [comment]
@pankajmt opened an issue https://github.com/dexidp/website/issues/161
