### ISSUE TITLE
group filter in Microsoft connector

### ISSUE THREAD

**Issue by jagadeesh-kancherla-tfs** [dexidp/dex#3385]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

We are using dex with ldap connector now switching to Microsoft connector, dex is getting all the groups from AD which causing issue for authentication

### Proposed Solution

Previously we are using ldap which have filter for groups
groupSearch:
baseDN: dc=test,dc=com
filter: "(&(objectCategory=Group)(name=K8S----))"

expecting similar group filter in Microsoft 

connectors:

type: microsoft
id: microsoft
name: Microsoft
config:
clientID:
clientSecret:
redirectURI:
tenant:

Is there any similar approach we have available in Microsoft connector?

**Comment by nabokihms** [comment]
@jagadeesh-kancherla-tfs Hello! I think you need to use `groups: ["a", "b", "c"]` along with `useGroupsAsWhitelist: true`.
https://github.com/dexidp/dex/blob/f6114706f62ee32cab29e5baf6a15491339a50b4/connector/microsoft/microsoft.go#L52-L54
