### ISSUE TITLE
[google connector] invalid kubernetes resource name

### ISSUE THREAD

**Issue by evgenii-avdiukhin** [dexidp/dex#3488]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.39.1

### Storage Type

Kubernetes

### Installation Type

Official Helm chart

### Expected Behavior

sucessfull authentification

### Actual Behavior

keep getting error with k8s resources failed to create

### Logs

```shell
time="2024-04-22T06:54:12Z" level=info msg="login successful: connector \"google\", username=\"Name Surname\", preferred_username=\"\", email=\"name.surname@domain.com\", groups=[]"
time="2024-04-22T06:54:12Z" level=error msg="Failed to get auth request: invalid kubernetes resource name: must match the pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and be no longer than 253 characters"
```

**Comment by evgenii-avdiukhin** [comment]
seems like dex is trying to create some kind of k8s resource using values he got from google, but he doesn't like length of some character like dot or space, just can't figure out what resource and what symbol he doesn't like
i see auth code and auth requests objects being created on request
thats my config
`connectors:
- config:
    clientID: my-client-id
    clientSecret: super-secret
    issuer: https://accounts.google.com
    redirectURI: http://dex.domain/callback
    scopes:
    - profile
    - email
  id: google
  name: Google
  type: google
enablePasswordDB: false
expiry:
  idTokens: 24h
  signingKeys: 6h
issuer: http://dex.domain
logger:
  level: debug
oauth2:
  alwaysShowLoginScreen: false
  skipApprovalScreen: true
staticClients:
- id: kubernetes
  name: kubernetes
  redirectURIs:
  - http://dex.k8s.domain/callback
  secret: secret
storage:
  config:
    inCluster: true
  type: kubernetes`

**Comment by nmattam** [comment]
@evgenii-avdiukhin Did you happen to find the cause of the error?
