### ISSUE TITLE
Debug logging not working

### ISSUE THREAD

**Issue by malins** [dexidp/dex#3495]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.39.1

### Storage Type

In-memory

### Installation Type

Official Helm chart

### Expected Behavior

I'm enabling debug logging in the configuration file.

### Actual Behavior

No debug messages are written, still getting only info and error messages.

### Configuration

```yaml
config:
  logger:
    level: "debug"
    format: "text"
```

**Comment by abhisek** [comment]
@malins Looking at the code I think `logger` should be a top level object and not nested inside `config`. Example

```
logger:
    level: "debug"
    format: "text"
```

I can see debug logs with the above config

```
➜  dex git:(master) ✗ ./bin/dex serve examples/config-dev.yaml
time="2024-04-25T08:46:33Z" level=info msg="Dex Version: 677ab3602040a05f335c651d1d8ae0b6938ec9a7, Go Version: go1.22.1, Go OS/ARCH: darwin arm64"
time="2024-04-25T08:46:33Z" level=info msg="config using log level: debug"
```

**Comment by abhisek** [comment]
@malins Yes. I see the same. There isn't too many debug log statements in the code. One example is when I stop the server I do see a debug log

```
time="2024-04-25T09:02:12Z" level=debug msg="starting graceful shutdown (telemetry)"
time="2024-04-25T09:02:12Z" level=debug msg="starting graceful shutdown (http)"
time="2024-04-25T09:02:12Z" level=info msg="received signal interrupt, shutdown now"
```
