### ISSUE TITLE
Expose additional HTTP metrics

### ISSUE THREAD

**Issue by IvoGoman** [dexidp/dex#3698]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Currently dex exposes only `http_requests_total{handler="", code="",method=""}` as a metric. The method used to calculate these metrics also collect the Duration and Response size written. https://github.com/felixge/httpsnoop/blob/master/capture_metrics.go#L46-L82
These metrics are not exposed.

### Proposed Solution

Additional histogram metrics:

- `http_request_duration_seconds{handler="", code="", method=""}` 
- `http_response_size_bytes{handler="", code="", method=""}`.

Which can be added to the handler instrumentalization here: https://github.com/dexidp/dex/blob/5c66c7186406e8c5e28aadb818dd8a2cb75b8442/server/server.go#L335-L356

Since native histograms are not yet GA, there is the open question of which Buckets make sense for these metrics.

**Comment by nabokihms** [comment]
@IvoGoman the idea seems nice. Would you like to go ahead and make the change?

**Comment by IvoGoman** [comment]
Yes, I will open a PR for this.
