### ISSUE TITLE
skipApprovalScreen: true is not skipping the grant access screen from version 2.39.0 and up 

### ISSUE THREAD

**Issue by vineeth-sri** [dexidp/dex#3707]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.39.1

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

Running on kubernetes version 1.29.5

oauth2:
      skipApprovalScreen: true
      responseTypes: ["id_token", "token", "code"]
      
      should skip the grant access page 
      

### Actual Behavior

      If I use the version 2.38.0 it works fine, not working in 2.39.1, 2.40.0 and 2.41.1

**Comment by nabokihms** [comment]
Probably a duplicate of https://github.com/dexidp/dex/issues/3540

**Comment by nabokihms** [comment]
The relying party asks Dex to show the approval screen. You need to change approval mode on the side of your application from force to anything else.

**Comment by vineeth-sri** [comment]
Thank you Sir
