### ISSUE TITLE
Is it possible to get a new release of the api/v2 go package?

### ISSUE THREAD

**Issue by marcofranssen** [dexidp/dex#3717]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

The https://pkg.go.dev/github.com/dexidp/dex/api/v2 hasn't got a new release for a long time.

### Proposed Solution

Cut a new release for the api/v2 package on a regular basis.

### Alternatives Considered

```
go get https://pkg.go.dev/github.com/dexidp/dex/api/v2@commit-hash
```

### Additional Information

I'm using this API for the Terraform provider https://github.com/marcofranssen/terraform-provider-dexidp

**Comment by marcofranssen** [comment]
Also see https://github.com/dexidp/dex/pull/2972#issuecomment-1975948535

**Comment by nabokihms** [comment]
I think yes, we missed it. It seems ok to release the new api package along with the dex release of there were changes

**Comment by marcofranssen** [comment]
Would love to see that 👍

**Comment by nabokihms** [comment]
https://pkg.go.dev/github.com/dexidp/dex/api/v2@v2.2.0
https://github.com/dexidp/website/pull/182
