### ISSUE TITLE
storage/sql: add tests for cockroach DB

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#390]
We've been looking for a distributed datastore for dex for a while now. With cockroachdb's beta, it looks like they've added support for `github.com/lib/pq` https://www.cockroachlabs.com/docs/build-a-test-app.html

Run some initial tests to see if dex can run with cockroachdb. Since dex doesn't use any especially unique SQL features, hopefully this will just work.

**Comment by srenatus** [comment]
#1343 made this obsolete. If someone wants to contribute another backend, that should include tests, and we might reopen this issue 😃
