### ISSUE TITLE
Run OpenID self-certification testing suits, and get an OpenID Certification

### ISSUE THREAD

**Issue by bobbyrullo** [dexidp/dex#42]
<a href="https://github.com/yifan-gu"><img src="https://avatars.githubusercontent.com/u/3278588?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yifan-gu](https://github.com/yifan-gu)**
_Friday Jul 24, 2015 at 19:36 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/336_

---

OpenID Foundation provides a series of testing suits to verify the OpenID Connect implementation:
http://openid.net/certification/
We should go through these process and run the testing suit against our authd implementation. We should at least pass the `OP basic` and `OP config` profile before open sourcing authd.

If we want to get the certification mark, we would need to become a member of the foundation and submit a request.

/cc @bobbyrullo @bcwaldon @philips

**Comment by estroz** [comment]
[Results](https://op.certification.openid.net:60307/display#OAuth) as of August 23rd 2017.

**Comment by karimhm** [comment]
Will ever DEX get certified?

**Comment by nabokihms** [comment]
I'm working on this one, and I would like to move it forward.

1. Certification process and basic test suite changed a little. We need to actualize our documentation about running certification tests.
2. The only major thing left is to implement sessions in dex.  In the current state, dex disrespect all sort of session-related stuff, including auth_time claim, `max age` and `prompt` options. I will open a new issue to discuss the design first.

Thus it looks like we are on our way to pass basic certification.

**Comment by sagikazarmark** [comment]
Progress will be tracked in this project: https://github.com/orgs/dexidp/projects/3/views/1

@nabokihms can you please open new issues and add them to this project if you have any details already? Thanks!
