### ISSUE TITLE
Back button doesn't work when using a password based login

### ISSUE THREAD

**Issue by roidelapluie** [dexidp/dex#549]
When you use a provider (LDAP, local) inside dex:
- When you choose LDAP or local connector, you arrive at the username and password form

Expected:
- There is a link to allow you to choose another provider that gets you back on the main page

Seen:
- That link does not exist

**Comment by ericchiang** [comment]
Does the back button on your browser suffice?

**Comment by roidelapluie** [comment]
If you POST wrong credential multiple times before noticing that you are using the wrong provider, back will not work (will ask to resend the POST data)

**Comment by ericchiang** [comment]
@roidelapluie thanks for the clarification.

**Comment by nabokihms** [comment]
The issue was fixed in Dex v2.29.0
https://github.com/dexidp/dex/pull/1865
