### ISSUE TITLE
Support multiple languages and locale matching

### ISSUE THREAD

**Issue by roidelapluie** [dexidp/dex#551]
It looks like there is not a lot of text in dex, so it would be great to be able to translate it, and to provide in the UI an easy way of switching language.

The default language could be either set from an option or take browser's default.

**Comment by ericchiang** [comment]
Practically, locale matching this going to be hard considering we have so much code that looks like this[0].

I don't think this is going to be possible on the main branch without a large overhaul. We'll try to keep this in mind for our V2 branch[1].

[0] https://github.com/coreos/dex/blob/043fcdadfadb5db804001598475d106e2ae55d20/server/http.go#L162
[1] https://github.com/coreos/dex/tree/dev

**Comment by sercand** [comment]
We definitely need this. Although it is a bad practice, currently we are achieving this by patching dex.

**Comment by nabokihms** [comment]
It is possible to translate HTML templates to the language. There are now so many screens to be a problem to maintain.
You can find the example here https://github.com/deckhouse/deckhouse/blob/e70e30b76cd4fa1fa755ddd24c595b7068123296/modules/150-user-authn/images/dex/web/templates/device.html#L21-L27

For now, Dex team does not have the capacity to provide more than one language support out of the box.

I'm going to close this. If you still want this feature to be implemented, please open a new issue.
