### ISSUE TITLE
cmd/dex: user filters

### ISSUE THREAD

**Issue by mjibson** [dexidp/dex#66]
We'd like to be able to restrict login to a service to any valid google account, for example `@coreos.com`.

**Comment by philips** [comment]
Has anyone thought about how this would be implemented? This is something I feel is necessary before we run a public dex.coreos.systems that is used to authenticate our users into our k8s clusters.

**Comment by bobbyrullo** [comment]
I think it could be done relatively easily with a flag + some logic in the registration code.

**Comment by bcwaldon** [comment]
Working on this.

**Comment by bcwaldon** [comment]
My first attempt was to add a check to the OIDC connector's callback handler, which effectively prevents any user from logging in to a remote OIDC Identity Provider. I left the code for this here: https://github.com/coreos/dex/tree/oidc-domain-filter. The UX provided by this solution isn't quite right, so I'm holding off on this until we figure out a better solution. The specific issue I ran into looks like this: you have two connectors, local and oidc, and registration is enabled (globally). My first approach would prevent users from registering via oidc if they weren't in the correct domain, but they could still create a local identity. 

It feels like we need to be able to disable registration globally, and per-connector. The specific use-case we are trying to solve for here requires that existing users can still log in regardless of whatever domain filtering is set up on the registration flow.

**Comment by ericchiang** [comment]
To expand on this, I think we'd like some form of user filters. Either globally to dex, per client, or per connector.

```
filter:
    whitelist:
        groups: ["foo"]
        emails: ["bar@coreos.com"]
```

Maybe expand into regexps or email domain.

**Comment by ericchiang** [comment]
FYI, after a lot of sitting on this I think this should probably be done by client apps instead of dex.

**Comment by ericchiang** [comment]
> FYI, after a lot of sitting on this I think this should probably be done by client apps instead of dex.

This approach actually doesn't work for users who want to use the public client or device flows (if we ever implement the latter). So there's still value in this proposal.

**Comment by srenatus** [comment]
#1371 seems to be a front page issue right now (😉) with a rather big overlap. 🧹 GCing this one, please bear with me.
