### ISSUE TITLE
Monitoring endpoints for debugging

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#778]
Add a Prometheus monitoring endpoint[0] or a pprof endpoint[1].

[0] https://github.com/prometheus/client_golang
[1] https://golang.org/pkg/net/http/pprof/

**Comment by ericchiang** [comment]
cc @rithujohn191 we've also had a request for adding additional prometheus metrics for connector availability etc.

**Comment by ericchiang** [comment]
For example, if the LDAP connector has connectivity.

**Comment by brancz** [comment]
Let us know if you want us to review ;)

**Comment by fabxc** [comment]
I'd recommend adding the debug pprof endpoint – we have it in Prometheus and it's pretty helpful. In general, client_go also comes with a default go collector that exposes all runtime internals (i.e. pprof metrics) we can gather. That's extremely helpful as well.

**Comment by byxorna** [comment]
It would be neat if this was prioritized for an upcoming release; having insight into the health and state of dex is critical when deployed into production environments. Not to mention, exposing a /metrics endpoint is part of being a good container-native citizen :)

**Comment by brancz** [comment]
@byxorna working on it: #1155

**Comment by sagikazarmark** [comment]
We have both metrics and pprof exposed on the telemetry endpoint.
