### ISSUE TITLE
Google IAM Groups extension

### ISSUE THREAD

**Issue by mwitkow** [dexidp/dex#866]
We're heavy users of Google GSuite and Google IAM. We're currently exploring expressing our Kubernetes cluster permissions as Google Admin Groups (e.g. `perms-cloud-prod@example.com`), similarly to how we group our Google IAM permissions with them.

Dex supports Google OpenID Connect login through `oicd` connector. However, we'd like to add a new connector that will:
 * use the oicd one as normal for fetching the `id_token` of the user
 * have a user-specfied Google IAM service account that has access to Google Admin APIs scope `https://www.googleapis.com/auth/admin.directory.group.readonly`
 * use the Google Admin API to query the user specified GSuite domain (`example.com`) groups that the users is part of (using https://developers.google.com/admin-sdk/directory/v1/reference/groups/list)
 * based on a user-config parameter filter the groups that match a prefix (e.g. `perms-`)

This would make it possible to use Google IAM group memberships and permissions for anyone who has a Google GSuite, similarly to how the Github Connector treats teams.

Would Dex be interested in such a feature?

**Comment by ericchiang** [comment]
Yeah sounds reasonable, though part of using groups is going to figure out how to connect refresh tokens with Google (there are some complications which make it difficult) https://github.com/coreos/dex/issues/863.

**Comment by mwitkow** [comment]
The groups reading would have to be done through a service account file (specified in the config), as it is unreasonable to expect every person in a Google GSuite domain to have admin rights, even if just readonly.

**Comment by melignus** [comment]
@mwitkow I have a use case for this too. I might take a stab at implementing this if someone else hasn't already?

**Comment by melignus** [comment]
Now that I think about it this might be justification for breaking Google out into it's own connector, google_oidc as the groups bit is going to have a lot of specific functionality? That might impact #959 and #974 as I think the "hd" is specific to Google's list of claims and would end up wrapped up in the Google specific oidc connector?

@roguePanda thoughts?

**Comment by melignus** [comment]
Just read @ericchiang's document, but the user access token will likely never have this scope available to them. I think @mwitkow is referring to a side request to the `admin.directory.group.readonly` scope using a service account flow from JWT.json?

[golang.org/x/oauth2/google#JWTConfigFromJSON](https://godoc.org/golang.org/x/oauth2/google#JWTConfigFromJSON
)and
[google.golang.org/api/admin/directory/v1#GroupsListCall](https://godoc.org/google.golang.org/api/admin/directory/v1#GroupsListCall
)
So then config would have a field for a service account .json issued from the Google API Console limited to reading the users groups and applying that to the id_token issued via dex back to the client.

@mwitkow I figure having a configurable prefix might be nice too, we use `acl-` for example?

**Comment by roguePanda** [comment]
@melignus I think splitting Google into its own connector makes a lot of sense. I can split my changes out from the oidc connector and leave the IAM support for another PR
