### ISSUE TITLE
Device Auth Flow support?

### ISSUE THREAD

**Issue by colemickens** [dexidp/dex#911]
Device Auth Flow: https://tools.ietf.org/html/draft-ietf-oauth-device-flow-05

Does Dex support a device auth flow for retrieving oauth/oidc tokens?

AADv1 supports it but not AADv2 which we need to use because AADv1 returns unsigned id_tokens upon refresh. It's unclear what the timeline is for device auth in AADv2, so I'm wondering what it would look like to use `dex` in front of AADv2. AADv2 will still be the "real" auth backend, but then we could use `dex` to perform the device authentication and shepherd the `id_token` and `refresh_token` back to the caller.

If Dex does not support this flow today, would y'all be amenable to someone adding support for it?

cc: @ericchiang since this is somewhat related to the [proposed Azure auth plugin for Kubernetes](https://github.com/kubernetes/kubernetes/pull/43987).

cc: @jmspring

**Comment by jmspring** [comment]
If it doesn't support it, I've got cycles to get this going.  If it does, I'm happy to make sure and document setup and use against Azure (amongst others).

**Comment by rithujohn191** [comment]
We currently do not support a device auth flow for retrieving tokens. We had a few quick questions regarding this request:
1) Noticed that the Device Auth Flow spec is still a draft and not yet an RFC, would it be acceptable that this implementation won't keep pace with the RFC changing?
2) Could you shed some more light on what all are the requirements to support this feature? Trying to estimate how much work this would actually be.

**Comment by joshuaballoch** [comment]
Wondering if there was any movement on this question, I'm looking to build an oauth 2 provider that supports the device flow as well.

I would be happy to give info on why I (think I) need to the proposed device flow.
