### ISSUE TITLE
Google open id HD param

### ISSUE THREAD

**Issue by stijndehaes** [dexidp/dex#959]
The google open id specification specifies the follow hd-param: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

This parameters allow you to specify for which domain users can log in. I can not find how to configure this in dex. I think however that this param is google specific so maybe that's why it is not used? I would love to use it to make sure that only user from our company can use this login.

Thanks for looking at my issue.
Stijn

**Comment by rithujohn191** [comment]
Hi @Steniaz ,

As of now we do not support the optional hd-param in our [OIDC connector](https://github.com/coreos/dex/blob/master/Documentation/oidc-connector.md) and it is not on our road map. However we would be more than happy to review a PR for this change if you can submit one.

thanks

**Comment by Steniaz** [comment]
@rithujohn191 Ok thanks for the help :) I'll see if I can do something in the coming weeks.

**Comment by rithujohn191** [comment]
Great thank you :)

**Comment by roguePanda** [comment]
I saw that it had been a while and needed this for my own purposes, so I put together a quick PR (#974). Let me know if it works for your use case @Steniaz!

**Comment by Steniaz** [comment]
@roguePanda Had a short look at your PR, this is exactly what I need thank you! Hopefully this can be merged pretty fast :)

**Comment by ericchiang** [comment]
I'd like this to be in a google specific connector and not in the OpenID Connect connector https://github.com/coreos/dex/issues/1001

**Comment by nabokihms** [comment]
The option is present in the specific Google connector and has been removed from the OIDC connector recently.
I think the initial problem was solved.
